### ISSUE TITLE
NoSuchFieldError on an instance at runtime

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/Mixin#112]
This is an odd one, I'm using an `@Inject` at the method head, and everything was seemingly fine, however I create a `MapData` instance and using reflection can see all the properties, including the `dimension` property that causes this error. I can even get the value through reflection. However at runtime I get `NoSuchFieldError` as you can see in the following stacktrace. The only thing I can think of is that during compilation it's a byte field (because I'm in `SpongeCommon`) but minecraft forge patches it to be an int at runtime. Which could mess with the bytecode output?

```java
@Inject(method = "onItemRightClick", at = @At(value = "HEAD"), cancellable = true)
    public void handleRightClick(ItemStack itemStackIn, World worldIn, EntityPlayer playerIn, CallbackInfoReturnable<ItemStack> ci) {
        ItemStack itemstack = new ItemStack(Items.filled_map, 1);

        Cause cause = Cause.of(NamedCause.source((Player) playerIn));
        InitializeMapEvent.CreateMapView event = SpongeEventFactory.createInitializeMapEventCreateMapView(cause, true);
        SpongeImpl.postEvent(event);

        // If we haven't cancelled and haven't overridden then replace the default id with a real one
        if (!event.isCancelled() && event.isUsingDefaultBehavior()) {
            itemstack.setItemDamage(DimensionManager.getWorldFromDimId(0).getUniqueDataId("map"));
            String s = "map_" + itemstack.getMetadata();
            MapData mapdata = new MapData(s);
            for (Field f : MapData.class.getDeclaredFields()) {
                f.setAccessible(true);
                try {
                    SpongeHooks.logInfo("{0}: {1}", f.getName(), f.get(mapdata));
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                }
            }
            DimensionManager.getWorldFromDimId(0).setItemData(s, mapdata);
            mapdata.scale = 0;
            mapdata.calculateMapCenter(playerIn.posX, playerIn.posZ, mapdata.scale);
            mapdata.dimension = (byte)worldIn.provider.getDimensionId();
            mapdata.markDirty();
        }

        ItemStack originalInput = itemStackIn.copy();

        Transaction<ItemStackSnapshot> replaceTransaction = new Transaction<>(ItemStackUtil.createSnapshot(originalInput),
                ItemStackUtil.createSnapshot(itemstack));

        // If we cancel the replacement, just return the input item, if we override, follow default logic, but use the new item.
        InitializeMapEvent.ReplaceMapItem replaceMapEvent = SpongeEventFactory.createInitializeMapEventReplaceMapItem(cause, replaceTransaction);
        SpongeImpl.postEvent(replaceMapEvent);

        if (replaceMapEvent.isCancelled()) {
            // Just cancel the whole return logic
            ci.setReturnValue(originalInput);
        } else {
            // Otherwise set the replacement item to the result of the transaction from the event
            itemstack = ItemStackUtil.toNative(replaceTransaction.getFinal().createStack());
        }

        --itemStackIn.stackSize;
        if (itemStackIn.stackSize <= 0)
        {
            ci.setReturnValue(itemstack);
            return;
        }
        else
        {
            if (!playerIn.inventory.addItemStackToInventory(itemstack.copy()))
            {
                playerIn.dropPlayerItemWithRandomChoice(itemstack, false);
            }

            playerIn.triggerAchievement(StatList.objectUseStats[Item.getIdFromItem(this)]);
            ci.setReturnValue(itemStackIn);
            return;
        }
    }
```

```
[09:07:43] [Server thread/INFO] [Sponge]: xCenter: 0
[09:07:43] [Server thread/INFO] [Sponge]: zCenter: 0
[09:07:43] [Server thread/INFO] [Sponge]: dimension: 0
[09:07:43] [Server thread/INFO] [Sponge]: scale: 0
[09:07:43] [Server thread/INFO] [Sponge]: colors: [B@43dd386d
[09:07:43] [Server thread/INFO] [Sponge]: playersArrayList: []
[09:07:43] [Server thread/INFO] [Sponge]: playersHashMap: {}
[09:07:43] [Server thread/INFO] [Sponge]: mapDecorations: {}
[09:07:43] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: dimension
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_77]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_77]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:736) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:365) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NoSuchFieldError: dimension
	at net.minecraft.item.ItemEmptyMap.handleRightClick(ItemEmptyMap.java:88) ~[ItemEmptyMap.class:?]
	at net.minecraft.item.ItemEmptyMap.onItemRightClick(ItemEmptyMap.java) ~[ItemEmptyMap.class:?]
	at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:170) ~[ItemStack.class:?]
	at net.minecraft.server.management.ItemInWorldManager.tryUseItem(ItemInWorldManager.java:364) ~[ItemInWorldManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.onActivateBlockOrUseItem(NetHandlerPlayServer.java:117) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayerBlockPlacement(NetHandlerPlayServer.java:617) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:70) ~[C08PacketPlayerBlockPlacement.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:10) ~[C08PacketPlayerBlockPlacement.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:106) ~[PacketUtil.class:?]
	at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(PacketThreadUtil.java:51) ~[PacketThreadUtil$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_77]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 5 more
```

**Comment by modwizcode** [comment]
After further research, I've determined the invalid bytecode theory (if it was even possible) is not the case as the final mixin bytecode does reference an int field.

**Comment by gabizou** [comment]
Are you sure that it's not because you're getting an empty map with nothing in it?

**Comment by modwizcode** [comment]
It's a freshly created instance. The error is trying to set the field. It
somehow isn't existing at app.

**Comment by modwizcode** [comment]
Seems I mistakenly viewed the wrong bytecode for the mixed inject. The issue is indeed a type conflict. I'm not sure how to resolve this, the type difference is the only difference between SpongeForge and SpongeVanilla, I'll keep poking, but maybe a mixin property for

**Comment by Zidane** [comment]
modwizcode, check into ```Coerce```, think that is what you want. May need to have both injections though.

**Comment by modwizcode** [comment]
`@Coerce` can't help, this isn't a local conversion, but rather a field access type change. I ended up working around it by implementing a series of `@Inject` and the like, however the resulting code is much harder to understand than the sample I wrote that causes the issue. Since the inject doesn't support locals, the use of multiple fields to maintain state is the messy result.

**Comment by Mumfrey** [comment]
Why don't you access the field via an accessor and simply overwrite the accessor with a downstream mixin?

**Comment by modwizcode** [comment]
That makes a lot of sense, I was completely over thinking it, although I
did successfully workaround the issue in tbis case. But won't the signature
of the overwritten accessor be wrong? Or are you suggesting I use a method
returning an int and just provide the overwrite to access it as a byte in
vanilla?

**Comment by Mumfrey** [comment]
Precisely.

**Comment by modwizcode** [comment]
I guess that's a proper solution, I'll close this for now.
