### ISSUE TITLE
Gradle problem, but not maven problem?

### ISSUE THREAD

**Issue by PizzaCrust** [SpongePowered/Mixin#113]
I encountered a weird situation with this framework. Maven was working, however Gradle was not.

This the log using Gradle:
```
2016-04-10 00:47:42,185 ERROR Error processing element Queue: CLASS_NOT_FOUND
2016-04-10 00:47:43,398 ERROR Unable to locate appender ServerGuiConsole for logger 
[00:47:43] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[00:47:43] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.5.3 Source=file:/home/---/Downloads/client/dml.jar Env=CLIENT
[00:47:43] [main/INFO]: Using primary tweak class name org.spongepowered.asm.launch.MixinTweaker
[00:47:43] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[00:47:43] [main/INFO]: Compatibility level set to JAVA_7
[00:47:43] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[00:47:43] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[00:47:43] [main/ERROR]: mixins.json:MixinMinecraft: Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above.
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validateClassVersion(MixinInfo.java:470) ~[dml.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validateMixin(MixinInfo.java:444) ~[dml.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:289) ~[dml.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:337) [dml.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:573) [dml.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:489) [dml.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:393) [dml.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:109) [dml.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [dml.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [dml.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_77]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_77]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_77]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_77]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [dml.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [dml.jar:?]
[00:47:43] [main/INFO]: Launching wrapped minecraft {pizzacrust.dml.DynamicMain}

```

build.gradle:
```groovy
group 'net.pizzacrust'
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'deobfuscate4j'

repositories {
    mavenCentral()
    maven {
        name 'sponge'
        url 'https://repo.spongepowered.org/maven'
    }
    maven {group 'net.pizzacrust'
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'deobfuscate4j'

repositories {
    mavenCentral()
    maven {
        name 'sponge'
        url 'https://repo.spongepowered.org/maven'
    }
    maven {
        name 'mojang'
        url 'https://libraries.minecraft.net'
    }
}

buildscript {
    repositories {
        mavenCentral()
        maven {
            name 'ionized'
            url 'https://raw.githubusercontent.com/QuantumTheoryMC/Ionized/master'
        }
    }
    dependencies {
        classpath 'qtmc.lib:DeobfMC:1.9-SNAPSHOT'
    }
}

deobfmc {
    downloadSrgLocation = 'https://raw.githubusercontent.com/ProjectTestificate/MinecraftMappings/master/1.9/obf2mcp.srg'
    downloadInJar = 'https://launcher.mojang.com/mc/game/1.9/client/2f67dfe8953299440d1902f9124f0f2c3a2c940f/client.jar'
    outJarName = 'Minecraft.jar'
}

dependencies {
    compile 'org.spongepowered:mixin:0.5.3-SNAPSHOT'
    compile files('libs/Minecraft.jar')
}

compileJava {
    sourceCompatibility = org.gradle.api.JavaVersion.VERSION_1_8
    targetCompatibility = org.gradle.api.JavaVersion.VERSION_1_8
}

jar {
    manifest {
        attributes('Main-Class': 'pizzacrust.dml.DynamicMain', 'MixinCompatibilityLevel': 'JAVA_7', 'MixinConfigs': 'mixins.json')
    }
    from {
        configurations.compile.collect {
            it.isDirectory() ? it : zipTree(it)
        }
        configurations.runtime.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}

        name 'mojang'
        url 'https://libraries.minecraft.net'
    }
}

buildscript {
    repositories {
        mavenCentral()
        maven {
            name 'ionized'
            url 'https://raw.githubusercontent.com/QuantumTheoryMC/Ionized/master'
        }
    }
    dependencies {
        classpath 'qtmc.lib:DeobfMC:1.9-SNAPSHOT'
    }
}

deobfmc {
    downloadSrgLocation = 'https://raw.githubusercontent.com/ProjectTestificate/MinecraftMappings/master/1.9/obf2mcp.srg'
    downloadInJar = 'https://launcher.mojang.com/mc/game/1.9/client/2f67dfe8953299440d1902f9124f0f2c3a2c940f/client.jar'
    outJarName = 'Minecraft.jar'
}

dependencies {
    compile 'org.spongepowered:mixin:0.5.3-SNAPSHOT'
    compile files('libs/Minecraft.jar')
}

compileJava {
    sourceCompatibility = org.gradle.api.JavaVersion.VERSION_1_8
    targetCompatibility = org.gradle.api.JavaVersion.VERSION_1_8
}

jar {
    manifest {
        attributes('Main-Class': 'pizzacrust.dml.DynamicMain', 'MixinCompatibilityLevel': 'JAVA_7', 'MixinConfigs': 'mixins.json')
    }
    from {
        configurations.compile.collect {
            it.isDirectory() ? it : zipTree(it)
        }
        configurations.runtime.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}
```

However, all is well when using Maven.

**Comment by gabizou** [comment]
If your source compatibility version and target compatibility version are for Java 8, then Mixin will expect the defined environment version to be Java 8. It seems that in your environment settings in your core mod, you're setting Java 7 compatibility, but the classes are compiled for Java 8.

**Comment by PizzaCrust** [comment]
Oh, it worked. Just changed MixinCompatiblityLevel into JAVA_8.
