### ISSUE TITLE
Failing to apply mixins doesn't report which injection failed and or why to be exact

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#115]
For the following error applying a mixin:
```
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Unexpecteded error whilst applying the mixin class
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:230) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:174) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:665) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:635) [mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:442) [mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:109) [mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_77]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_77]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:536) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:379) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:115) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at com.mumfrey.liteloader.debug.Start.main(Start.java:53) [liteloader-1.9-SNAPSHOT.jar:1.9-SNAPSHOT+unknown-b0.git-unknown]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]
Caused by: org.spongepowered.asm.mixin.injection.struct.InvalidMemberDescriptorException: Invalid name: net/minecraft/client/renderer/EntityRenderer;setupFog
	at org.spongepowered.asm.mixin.injection.struct.MemberInfo.validate(MemberInfo.java:297) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.MemberInfo.parseAndValidate(MemberInfo.java:440) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionPointData.getTarget(InjectionPointData.java:125) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.points.BeforeInvoke.<init>(BeforeInvoke.java:90) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.InjectionPoint.parse(InjectionPoint.java:382) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.InjectionPoint.parse(InjectionPoint.java:353) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:192) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:148) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:39) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:415) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:927) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.prepareInjections(MixinApplicator.java:761) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMixin(MixinApplicator.java:251) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:220) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	... 30 more
```
The `@Redirect` was simply reading:
```java
    @Redirect(method = "renderWorldPass", at = @At(value = "INVOKE", target = "net/minecraft/client/renderer/EntityRenderer;setupFog(IF)V"))
```

What could be added is simply to say "here's the found annotation" and print the entire annotation for which method is being read. In general, this would end up being perfectly valid if an extra `L` was included, but I digress.

**Comment by Mumfrey** [comment]
I can't really give the annotation unless I completely reconstruct it, but I can make the exception itself a bit more descriptive and provide some more context.
