### ISSUE TITLE
MirrorUtils crashing on bounded type generics

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#116]
Similar to the issues with `TYPEVAR` with Java 7+, the following is producing the issue with MirrorUtils:

```java
    public <T extends Comparable<T>, V extends T> IBlockState withProperty(IProperty<T> property, V value) {

```

```
Caused by: java.lang.IllegalArgumentException: Unable to compute upper bound of type symbol V
        at org.spongepowered.tools.MirrorUtils.getUpperBound(MirrorUtils.java:254)
        at org.spongepowered.tools.MirrorUtils.getTypeName(MirrorUtils.java:196)
        at org.spongepowered.tools.MirrorUtils.getJavaSignature(MirrorUtils.java:167)
        at org.spongepowered.tools.obfuscation.AnnotatedMixinElementHandler.validateTargetMethod(AnnotatedMixinElementHandler.java:325)
        at org.spongepowered.tools.obfuscation.AnnotatedMixinOverwriteHandler.registerOverwrite(AnnotatedMixinOverwriteHandler.java:48)
        at org.spongepowered.tools.obfuscation.AnnotatedMixin.registerOverwrite(AnnotatedMixin.java:342)
        at org.spongepowered.tools.obfuscation.AnnotatedMixins.registerOverwrite(AnnotatedMixins.java:352)
        at org.spongepowered.tools.obfuscation.TargetObfuscationProcessor.processOverwrites(TargetObfuscationProcessor.java:117)
        at org.spongepowered.tools.obfuscation.TargetObfuscationProcessor.process(TargetObfuscationProcessor.java:63)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 76 more

```

**Comment by gabizou** [comment]
Just to provide a way to replicate the issue: Clone SpongeForge at this commit: https://github.com/SpongePowered/SpongeForge/tree/f46e8f29d37e070d551cf86e58d978780d7e1ca5 and try building the project.

**Comment by Mumfrey** [comment]
Can I just say for the record that I bloody hate Mirror when it comes to generics. Should not be hard to fix though because that exception is one I'm throwing myself from a case I hoped wouldn't be reached.

**Comment by Mumfrey** [comment]
Woo, that was simple. It turns out that if you ask a TYPEVAR for its upper bound, the upper bound *itself* can be a TYPEVAR, thus you just need to recurse into it until you find the *actual* upper bound. I've picked an arbitrary max depth of 5. If we find any generics more complex than that then it's probably your fault!

Committing fix now.
