### ISSUE TITLE
Error when Mixin specified in configuration is not found is ignored, even if the Mixin is required.

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#122]
When Mixin specified in configuration file is not found (even if specified as required) the stacktrace is printed to console and exception is ignored, it's not passed to IMixinErrorHandler.

While such error should never happen in production, spotting such exception in the early log spam is very hard, especially when it's not expected. 

Example stacktrace (from dev environment):

    java.lang.ClassNotFoundException: The specified mixin 'cubicchunks.asm.mixin.client.MixinRenderGlobal_EntityRenderFix' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:734) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:274) ~[mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initialiseMixins(MixinConfig.java:377) [mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initialise(MixinConfig.java:316) [mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:562) [mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:495) [mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:405) [mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:112) [mixin-0.5.3-SNAPSHOT.jar:0.5.3-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_72-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_72-internal]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_72-internal]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_72-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]

**Comment by Mumfrey** [comment]
This was brought to my attention last week and provision was made for it in 0.5.4.
