### ISSUE TITLE
Mixing into Interfaces with Lambdas

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#148]
There's an issue with the following for mixing into an interface:

The interface (from SpongeAPI):
```java
package org.spongepowered.api.item.merchant;

import org.spongepowered.api.data.DataHolder;
import org.spongepowered.api.data.manipulator.mutable.entity.TradeOfferData;
import org.spongepowered.api.entity.living.Humanoid;
import org.spongepowered.api.item.inventory.Carrier;
import org.spongepowered.api.world.Locatable;

import java.util.Optional;

import javax.annotation.Nullable;

/**
 * Represents a Merchant which can offer trades to customers.
 */
public interface Merchant extends DataHolder, Carrier, Locatable {

    /**
     * Gets the currently trading customer with this merchant.
     *
     * @return The currently trading customer if available
     */
    Optional<Humanoid> getCustomer();

    /**
     * Sets the currently trading customer with this merchant.
     * <p>If the humanoid entity is available, a new trading window may open
     * with this merchant.</p>
     *
     * @param humanoid The humanoid to trade with
     */
    void setCustomer(@Nullable Humanoid humanoid);

    /**
     * Gets a copy of the used {@link TradeOfferData} containing all available
     * {@link TradeOffer}s this {@link Merchant} may use.
     *
     * @return A copy of the trade offer data
     */
    default TradeOfferData getTradeOfferData() {
        return get(TradeOfferData.class).get();
    }

}
```

And the provided mixin:

```java
package org.spongepowered.common.mixin.api.item.merchant;

import net.minecraft.entity.IMerchant;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.ItemStack;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.TextComponentString;
import net.minecraft.village.MerchantRecipe;
import net.minecraft.village.MerchantRecipeList;
import net.minecraft.world.World;
import org.spongepowered.api.entity.living.Humanoid;
import org.spongepowered.api.item.merchant.Merchant;
import org.spongepowered.api.item.merchant.TradeOffer;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.common.interfaces.world.IMixinLocation;

import javax.annotation.Nullable;

@Mixin(value = Merchant.class, remap = false)
public interface MixinMerchant extends Merchant, IMerchant {

    @Override
    default void setCustomer(EntityPlayer player) {
        this.setCustomer((Humanoid) player);
    }

    @Override
    default EntityPlayer mth_000385_s_() {
        return this.getCustomer().map(humanoid -> humanoid instanceof EntityPlayer ? (EntityPlayer) humanoid : null).orElse(null);
    }

    @Nullable
    @Override
    default MerchantRecipeList getRecipes(EntityPlayer player) {
        final MerchantRecipeList merchantRecipes = new MerchantRecipeList();
        for (TradeOffer tradeOffer : getTradeOfferData().tradeOffers()) {
            merchantRecipes.add((MerchantRecipe) tradeOffer);
        }
        return merchantRecipes;
    }

    @Override
    default void useRecipe(MerchantRecipe recipe) {

    }

    @Override
    default void verifySellingItem(ItemStack stack) {

    }

    @Override
    default ITextComponent getDisplayName() {
        return new TextComponentString("nitwit");
    }

    @Override
    default World mth_000390_t_() {
        return ((World) getLocation().getExtent());
    }

    @Override
    default BlockPos mth_000391_u_() {
        return ((IMixinLocation) (Object) getLocation()).getBlockPos();
    }
}
```

At load time, the application ends up failing to apply with the following stack trace:
```
[22:12:28] [main/ERROR] [mixin]: mixins.common.api.json:item.merchant.MixinMerchant: Interface mixin contains a non-public method! Found lambda$mth_000385_s_$0(Lorg/spongepowered/api/entity/living/Humanoid;)Lnet/minecraft/entity/player/EntityPlayer; in mixins.common.api.json:item.merchant.MixinMerchant
org.spongepowered.asm.mixin.transformer.throwables.InvalidInterfaceMixinException: Interface mixin contains a non-public method! Found lambda$mth_000385_s_$0(Lorg/spongepowered/api/entity/living/Humanoid;)Lnet/minecraft/entity/player/EntityPlayer; in mixins.common.api.json:item.merchant.MixinMerchant
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorInterface.prepareMethod(MixinPreProcessorInterface.java:61) ~[mixin-0.5.17-SNAPSHOT.jar:0.5.17-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.prepare(MixinPreProcessorStandard.java:114) ~[mixin-0.5.17-SNAPSHOT.jar:0.5.17-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:264) ~[mixin-0.5.17-SNAPSHOT.jar:0.5.17-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:709) ~[mixin-0.5.17-SNAPSHOT.jar:0.5.17-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:426) [mixin-0.5.17-SNAPSHOT.jar:0.5.17-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:665) [mixin-0.5.17-SNAPSHOT.jar:0.5.17-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [mixin-0.5.17-SNAPSHOT.jar:0.5.17-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:481) [mixin-0.5.17-SNAPSHOT.jar:0.5.17-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:185) [mixin-0.5.17-SNAPSHOT.jar:0.5.17-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_102]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_102]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_102]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStartServer.main(GradleStartServer.java:10) [start/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:?]
```

Now, the issue is somewhat clear that lambdas are not proper methods but default implemented methods in the interface, granted, I feel that this is an error on Mixin's behalf.

**Comment by Mumfrey** [comment]
Basically another case where I need to suppress an error when something is synthetic by the looks of it.
