### ISSUE TITLE
Spongeforge and Mixin 0.6.15+

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/Mixin#221]
Spongeforge: 1.11.2-2476-6.1.0-BETA-2699
Mixin: 0.6.15+

project: https://github.com/ImMorpheus/Orion/tree/da3dbfb97d0f49d5563c7d164e3c5e26c22d9666
Changing mixin to anything newer than 0.6.14 and using "run server" results in:
```

[18:41:39] [main/ERROR] [mixin]: mixins.common.api.json:item.merchant.MixinMerchant: func_70932_a_ does not exist in target interface net.minecraft.entity.IMerchant
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: func_70932_a_ does not exist in target interface net.minecraft.entity.IMerchant
	at org.spongepowered.asm.mixin.transformer.InterfaceInfo.renameMethod(InterfaceInfo.java:188) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.prepareSoftImplements(MixinPreProcessorStandard.java:154) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.prepareMethod(MixinPreProcessorStandard.java:135) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorInterface.prepareMethod(MixinPreProcessorInterface.java:65) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.prepare(MixinPreProcessorStandard.java:123) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validateChanges(MixinInfo.java:389) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:291) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:801) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:499) [mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:779) [mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:668) [mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:647) [mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:557) [mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184) [mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_141]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_141]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_141]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStartServer.main(GradleStartServer.java:10) [start/:?]
[18:41:40] [main/FATAL] [mixin]: Mixin apply failed mixins.common.core.json:server.MixinMinecraftServer -> net.minecraft.server.MinecraftServer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Overwrite target "func_71247_a" was not located in target class net/minecraft/server/MinecraftServer
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Overwrite target "func_71247_a" was not located in target class net/minecraft/server/MinecraftServer
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:447) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:416) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:398) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:290) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:259) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:332) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:834) [mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:804) [mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:609) [mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184) [mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_141]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_141]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_141]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStartServer.main(GradleStartServer.java:10) [start/:?]
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.common.core.json:server.MixinMinecraftServer] from phase [DEFAULT] in config [mixins.common.core.json] FAILED during APPLY
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:900)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:853)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:613)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.Class.forName0(Native Method)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.Class.forName(Class.java:348)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[18:41:40] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transform:619]: 	at GradleStartServer.main(GradleStartServer.java:10)
[18:41:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Overwrite target "func_71247_a" was not located in target class net/minecraft/server/MinecraftServer
[18:41:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:447)
[18:41:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:416)
[18:41:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:398)
[18:41:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:290)
[18:41:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:259)
[18:41:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:332)
[18:41:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:834)
[18:41:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:804)
[18:41:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:609)
[18:41:40] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 15 more
[18:41:40] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.server.MinecraftServer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_141]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_141]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStartServer.main(GradleStartServer.java:10) [start/:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:621) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.common.core.json:server.MixinMinecraftServer] from phase [DEFAULT] in config [mixins.common.core.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:900) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:853) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:613) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Overwrite target "func_71247_a" was not located in target class net/minecraft/server/MinecraftServer
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:447) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:416) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:398) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:290) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:259) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:332) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:834) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:804) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:609) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184) ~[mixin-0.6.15-SNAPSHOT.jar:0.6.15-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	... 12 more
```

I'm almost sure I'm doing something wrong.

**Comment by Mumfrey** [comment]
Versions of Mixin prior to 0.7.(x I can't remember which) had issues when running in obfuscated environments where the consumed library is being used as a deobfDep. Update mixin to latest version and Sponge to latest bleeding and test again, reference also issues #207 and #215.

**Comment by ImMorpheus** [comment]
Whoops, forgot this. 
I tried creating a 1.12 mod, however "StartServer" crashes as soon as the server starts.

```
[18:11:28] [main/INFO] [GradleStart]: Extra: [nogui]
[18:11:28] [main/INFO] [GradleStart]: Running with arguments: [--tweakClass, net.minecraftforge.fml.common.launcher.FMLServerTweaker, nogui, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[18:11:28] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[18:11:28] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[18:11:28] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[18:11:28] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
Exception in thread "main" 
Exception: java.lang.IncompatibleClassChangeError thrown from the UncaughtExceptionHandler in thread "main"
```
Removing MixinGradle seems to make the server start. (obv it doesn't fix the problem).
No luck with cleanCache (forgegradle task).
Note: The class is not really empty, I'm using MinecraftDev.
