### ISSUE TITLE
Injection failed

### ISSUE THREAD

**Issue by VRCube** [SpongePowered/Mixin#237]
MIXIN Subsystem Version: 0.6.4
Mapping: NOTCH Stable_20
Target Version: 1.8.9

It works in development environment but not with launcher
Stacktrace: 
```[14:51:03] [main/INFO]: Mixing MixinMinecraft from mixins.Hyperium.json into ave
[14:51:04] [main/FATAL]: Mixin apply failed mixins.Hyperium.json:MixinMinecraft -> ave: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Inject annotation on handler$init$zza000 could not find 'startGame'
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$init$zza000 could not find 'startGame'
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:337) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:140) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:127) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:42) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:369) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1025) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:862) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:289) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:254) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:263) ~[Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:731) [Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:701) [Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:527) [Hyperium-1.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:182) [Hyperium-1.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:267) [launchwrapper-1.7.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:165) [launchwrapper-1.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:41) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.7.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27) [launchwrapper-1.7.jar:?]
```

**Comment by VRCube** [comment]
refmap was wrong in mixin config

**Comment by Mumfrey** [comment]
You should use a more recent version of Mixin, in later versions this error message will actually tell you which refmap is active (or none) so it makes it much more obvious when an injector is failing simply because the refmap has not been loaded.
