### ISSUE TITLE
Back off when a conflicting mixin is detected from another mod you accounted for

### ISSUE THREAD

**Issue by TerminatorNL** [SpongePowered/Mixin#281]
I am dealing with another mod, namely: SpongeForge that uses `@Redirect` and `@Overwrite`'s on methods I wished to intercept. This will result in Mixin conflicts, this makes total sense to me.

I circumvented this problem by `@Redirect`ing the same method in SpongeForge.

However, I only want to do this approach when SpongeForge is actually present. I simply lowered the priority of my own Mixins, making sure SpongeForge gets them first.

This approach however, does raise warnings when loading.

<details><summary>Warning type 1</summary>
<p>

```
[23:46:19] [main/WARN] [mixin]: Mixin apply failed mixins.laggoggles.json:MixinWorld -> net.minecraft.world.World: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/World::redirect$onUpdateTileEntities$zpm001 with priority 999 cannot inject into net/minecraft/world/World::func_72939_s()V merged by org.spongepowered.common.mixin.core.world.MixinWorld with priority 1000
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/World::redirect$onUpdateTileEntities$zpm001 with priority 999 cannot inject into net/minecraft/world/World::func_72939_s()V merged by org.spongepowered.common.mixin.core.world.MixinWorld with priority 1000
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:229) ~[LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:176) ~[LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:257) ~[LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1186) ~[LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:929) ~[LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:317) ~[LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280) ~[LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [LagGoggles-FORGE-1.12.2-5.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_171]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_171]
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048) [?:1.8.0_171]
	at java.lang.Class.getMethod0(Class.java:3018) [?:1.8.0_171]
	at java.lang.Class.getMethod(Class.java:1784) [?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge-1.12.2-14.23.4.2705-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge-1.12.2-14.23.4.2705-universal.jar:?]
```
</p></details>

<details><summary>Warning type 2</summary>
<p>

```
[23:46:19] [main/WARN] [mixin]: @Redirect conflict. Skipping mixins.laggoggles.json:MixinWorldServer->@Redirect::redirect$onBlockTick$zpn001(Lnet/minecraft/block/Block;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;Ljava/util/Random;)V with priority 999, already redirected by mixins.common.core.json:world.MixinWorldServer->@Redirect::redirect$onUpdateTick$zlp000(Lnet/minecraft/block/Block;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;Ljava/util/Random;)V with priority 1000
[23:46:19] [main/WARN] [mixin]: @Redirect conflict. Skipping mixins.laggoggles.json:MixinWorldServer->@Redirect::redirect$onBlockTick$zpn001(Lnet/minecraft/block/Block;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;Ljava/util/Random;)V with priority 999, already redirected by mixins.common.core.json:world.MixinWorldServer->@Redirect::redirect$spongeBlockUpdateTick$zlp000(Lnet/minecraft/block/Block;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;Ljava/util/Random;)V with priority 1000
```
</p></details>
<br>

What this all boils down to is... _Is there a way to disable my own mixins if SpongeForge is present?_ 

and: _Is there a way to disable my own mixins if SpongeForge is **not** present?_

Thanks again for your time, and maintaining Mixin.

**Comment by TerminatorNL** [comment]
Forgot to mention: This is purely cosmetic, the server will still start and everything will work as intended. This is just about suppressing the warnings, because they are accounted for.

**Comment by Barteks2x** [comment]
Create a (mixin config plugin)[https://github.com/SpongePowered/Mixin/blob/2c72246fe0b67c145db5510e66c8873df18b5a9f/src/main/java/org/spongepowered/asm/mixin/extensibility/IMixinConfigPlugin.java].

**Comment by TerminatorNL** [comment]
Thanks for this! I must have completely overlooked this.
Have a nice day!
