### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by Thiece** [SpongePowered/Mixin#283]
I have encountered some problems. The same file, I am able to run normally on my computer with better performance. When I migrated it to my other computer, this error occurred. I don't know how to debug it.

```
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge-1.12.2-14.23.4.2705-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge-1.12.2-14.23.4.2705-universal.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/management/PlayerProfileCache$ProfileEntry
	at net.minecraft.server.management.PlayerProfileCache.<init>(SourceFile:60) ~[ph.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1541) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.management.PlayerProfileCache$ProfileEntry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at net.minecraft.server.management.PlayerProfileCache.<init>(SourceFile:60) ~[ph.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1541) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/common/interfaces/server/management/IMixinPlayerProfileCacheEntry
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_181]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at net.minecraft.server.management.PlayerProfileCache.<init>(SourceFile:60) ~[ph.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1541) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.common.interfaces.server.management.IMixinPlayerProfileCacheEntry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_181]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at net.minecraft.server.management.PlayerProfileCache.<init>(SourceFile:60) ~[ph.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1541) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.jar.Attributes.<init>(Attributes.java:84) ~[?:1.8.0_181]
	at java.util.jar.Attributes.clone(Attributes.java:291) ~[?:1.8.0_181]
	at sun.net.www.protocol.jar.URLJarFile.getManifest(URLJarFile.java:155) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:147) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_181]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_181]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at net.minecraft.server.management.PlayerProfileCache.<init>(SourceFile:60) ~[ph.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1541) ~[MinecraftServer.class:?]
	... 12 more
```

**Comment by Thiece** [comment]
@Aaron1011 Thank you. After adjusting XMX, it will be normal. Is this the default parameter?
