### ISSUE TITLE
IllegalAccessError: no such constructor

### ISSUE THREAD

**Issue by pKalju** [SpongePowered/Mixin#287]
Original function in AbstractHorse.class:
```
public double getHorseJumpStrength() {
    return this.getAttribute(JUMP_STRENGTH).getAttributeValue();
}
```

My Mixin class:
```
@Mixin(AbstractHorse.class)
public abstract class MixinAbstractHorse extends MixinEntityLivingBase {
    @Inject(method = "getHorseJumpStrength", at = @At(value = "RETURN"), cancellable = true)
    private void onGetHorseJumpStrength(CallbackInfoReturnable<Double> ci) {
        System.out.println(ci.getReturnValue());
    }
}
```

Stacktrace:
```
[19:48:07] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: net.minecraft.entity.passive.EntityDonkey.<init>(World)void/newInvokeSpecial
	at net.minecraft.entity.EntityType.<clinit>(SourceFile:148) ~[EntityType.class:?]
	at net.minecraft.init.Bootstrap.register(SourceFile:470) ~[Bootstrap.class:?]
	at net.minecraft.client.Minecraft.<init>(SourceFile:370) ~[Minecraft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 12 more
Caused by: java.lang.IllegalAccessError: no such constructor: net.minecraft.entity.passive.EntityDonkey.<init>(World)void/newInvokeSpecial
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483) ~[?:1.8.0_162]
	at net.minecraft.entity.EntityType.<clinit>(SourceFile:148) ~[EntityType.class:?]
	at net.minecraft.init.Bootstrap.register(SourceFile:470) ~[Bootstrap.class:?]
	at net.minecraft.client.Minecraft.<init>(SourceFile:370) ~[Minecraft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 12 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/entity/passive/AbstractHorse.getHorseJumpStrength()D @12: dup
  Reason:
    Type double_2nd (current frame, stack[1]) is not assignable to category1 type
  Current Frame:
    bci: @12
    flags: { }
    locals: { 'net/minecraft/entity/passive/AbstractHorse' }
    stack: { double, double_2nd }
  Bytecode:
    0x0000000: 2ab2 022a b602 2eb9 0233 0100 5948 bb02
    0x0000010: 3559 1302 3604 27b7 0239 4c2a 2bb7 023d
    0x0000020: 2bb6 0240 9900 082b b602 43af af       
  Stackmap Table:
    full_frame(@44,{Object[#2],Object[#565]},{Double})

	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_162]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_162]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_162]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_162]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_162]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_162]
	at net.minecraft.entity.EntityType.<clinit>(SourceFile:148) ~[EntityType.class:?]
	at net.minecraft.init.Bootstrap.register(SourceFile:470) ~[Bootstrap.class:?]
	at net.minecraft.client.Minecraft.<init>(SourceFile:370) ~[Minecraft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[Main.class:?]
	... 12 more
Disconnected from the target VM, address: '127.0.0.1:58594', transport: 'socket'

Process finished with exit code 1
```

**Comment by Mumfrey** [comment]
Reading this stacktrace I think the actual underlying issue is handling of the `double` return type of the method you're injecting into. I'll need to take a look into it to verify that though. You could try to get a more scientifici result by using `-Dmixin.debug.verify=true` to enable the verifier and it should hopefully crash earlier on in the Class Verifier instead.

**Comment by pKalju** [comment]
```
org.spongepowered.asm.lib.tree.analysis.AnalyzerException: Error at instruction 7: Illegal use of DUP
	at org.spongepowered.asm.lib.tree.analysis.Analyzer.analyze(Analyzer.java:295)
	at org.spongepowered.asm.lib.util.CheckMethodAdapter$1.visitEnd(CheckMethodAdapter.java:453)
	at org.spongepowered.asm.lib.MethodVisitor.visitEnd(MethodVisitor.java:878)
	at org.spongepowered.asm.lib.util.CheckMethodAdapter.visitEnd(CheckMethodAdapter.java:1037)
	at org.spongepowered.asm.lib.tree.MethodNode.accept(MethodNode.java:838)
	at org.spongepowered.asm.lib.tree.MethodNode.accept(MethodNode.java:727)
	at org.spongepowered.asm.lib.tree.ClassNode.accept(ClassNode.java:412)
	at org.spongepowered.asm.mixin.transformer.ext.extensions.ExtensionCheckClass.postApply(ExtensionCheckClass.java:87)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:162)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:706)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.entity.EntityType.<clinit>(SourceFile:148)
	at net.minecraft.init.Bootstrap.register(SourceFile:470)
	at net.minecraft.client.Minecraft.<init>(SourceFile:370)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)
Caused by: org.spongepowered.asm.lib.tree.analysis.AnalyzerException: Illegal use of DUP
	at org.spongepowered.asm.lib.tree.analysis.Frame.execute(Frame.java:338)
	at org.spongepowered.asm.lib.tree.analysis.Analyzer.analyze(Analyzer.java:200)
	... 43 more
[17:00:04] [main/INFO]: Error at instruction 7: Illegal use of DUP getHorseJumpStrength()D
00000 R .  :     :    L0
00001 R .  :     :    L1
00002 R .  :     :     LINENUMBER 344 L1
00003 R .  :     :     ALOAD 0
00004 R .  : R   :     GETSTATIC net/minecraft/entity/passive/AbstractHorse.JUMP_STRENGTH : Lnet/minecraft/entity/ai/attributes/IAttribute;
00005 R .  : R R  :     INVOKEVIRTUAL net/minecraft/entity/passive/AbstractHorse.getAttribute (Lnet/minecraft/entity/ai/attributes/IAttribute;)Lnet/minecraft/entity/ai/attributes/IAttributeInstance;
00006 R .  : R   :     INVOKEINTERFACE net/minecraft/entity/ai/attributes/IAttributeInstance.getAttributeValue ()D
00007 R .  : D   :     DUP
00008 ?          :     DSTORE 1
00009 ?          :     NEW org/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable
00010 ?          :     DUP
00011 ?          :     LDC "getHorseJumpStrength"
00012 ?          :     ICONST_1
00013 ?          :     DLOAD 1
00014 ?          :     INVOKESPECIAL org/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable.<init> (Ljava/lang/String;ZD)V
00015 ?          :     ASTORE 1
00016 ?          :     ALOAD 0
00017 ?          :     ALOAD 1
00018 ?          :     INVOKESPECIAL net/minecraft/entity/passive/AbstractHorse.handler$onGetHorseJumpStrength$zzb000 (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V
00019 ?          :     ALOAD 1
00020 ?          :     INVOKEVIRTUAL org/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable.isCancelled ()Z
00021 ?          :     IFEQ L2
00022 ?          :     ALOAD 1
00023 ?          :     INVOKEVIRTUAL org/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable.getReturnValueD ()D
00024 ?          :     DRETURN
00025 ?          :    L2
00026 ?          :     DRETURN
00027 ?          :    L3
00028 ?          :    L4

```

**Comment by Mumfrey** [comment]
Yep, that confirms it. The `DUP` opcode is there to "grab" the return value from the stack so it can be captured into the `CallbackInfoReturnable` but because the return type is `double` then it **should** be `DUP2`.
