### ISSUE TITLE
Mixin removes `get` prefix for invokers

### ISSUE THREAD

**Issue by Runemoro** [SpongePowered/Mixin#294]
It seems like Mixin removes the `get` prefix of an `@Invoker` method when searching for the target method:

```
[00:14:23] [main/FATAL]: Mixin apply failed mixins.toomanycrashes.json:MixinCrashReportElement$ElementAccessor -> net.minecraft.util.crash.CrashReportElement$Element: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching name()Ljava/lang/String; in net/minecraft/util/crash/CrashReportElement$Element for mixins.toomanycrashes.json:MixinCrashReportElement$ElementAccessor->@Invoker[METHOD_PROXY]::getName()Ljava/lang/String;
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching name()Ljava/lang/String; in net/minecraft/util/crash/CrashReportElement$Element for mixins.toomanycrashes.json:MixinCrashReportElement$ElementAccessor->@Invoker[METHOD_PROXY]::getName()Ljava/lang/String;
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382) ~[sponge-mixin-0.7.11.13.jar:0.7.11.13+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.gen.InvokerInfo.findTargetMethod(InvokerInfo.java:62) ~[sponge-mixin-0.7.11.13.jar:0.7.11.13+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.gen.InvokerInfo.locate(InvokerInfo.java:58) ~[sponge-mixin-0.7.11.13.jar:0.7.11.13+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1215) ~[sponge-mixin-0.7.11.13.jar:0.7.11.13+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:947) ~[sponge-mixin-0.7.11.13.jar:0.7.11.13+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:321) ~[sponge-mixin-0.7.11.13.jar:0.7.11.13+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280) ~[sponge-mixin-0.7.11.13.jar:0.7.11.13+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[sponge-mixin-0.7.11.13.jar:0.7.11.13+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [sponge-mixin-0.7.11.13.jar:0.7.11.13+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [sponge-mixin-0.7.11.13.jar:0.7.11.13+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [sponge-mixin-0.7.11.13.jar:0.7.11.13+unknown-b0.git-unknown]
```

The mixin:
```java
    @Mixin(targets = "net.minecraft.util.crash.CrashReportElement$Element")
    private interface ElementAccessor {
        @Invoker String getName();
        @Invoker String getDetail();
    }
```

Changing `getName` to `getGetName` and `getDetail` to `getGetDetail` fixes the issue.

**Comment by Pokechu22** [comment]
It looks like you're supposed to use the names `invokeGetDetail` or `callGetDetail`.



It accepting `getGetName` seems like it's probably a bug; regular accessors will yell at you if you name them using `invoke` or `call` as far as I can tell so I'd expect invokers to do the same if used another way.

**Comment by Runemoro** [comment]
Thanks!
