### ISSUE TITLE
Accessor/Invoker Mixins cannot be accessed from other Mixin injections

### ISSUE THREAD

**Issue by asiekierka** [SpongePowered/Mixin#305]
I'm not sure if this is out of scope (absolutely fine if it is - after all, it's easy to work around), but reporting for the sake of information.

Let's take the following hook:

```
	@Inject(method = "onCustomPayload", at = @At("HEAD"), cancellable = true)
	public void onCustomPayload(CustomPayloadC2SPacket packet, CallbackInfo info) {
		CustomPayloadC2SPacketAccessor accessor = (CustomPayloadC2SPacketAccessor) packet;
		Identifier id = accessor.getChannel();
		[...]
```

Where CustomPayloadC2SPacketAccessor is as follows:

```
@Mixin(CustomPayloadC2SPacket.class)
public interface CustomPayloadC2SPacketAccessor {
	@Accessor
	Identifier getChannel();
	@Accessor
	PacketByteBuf getData();
}
```

will fail to apply with the following error:

```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [net.fabricmc.fabric.mixins.common.json:networking.MixinServerPlayNetworkHandler] from phase [DEFAULT] in config [net.fabricmc.fabric.mixins.common.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Resolution error: unable to find corresponding type for net/fabricmc/fabric/mixin/networking/CustomPayloadC2SPacketAccessor in hierarchy of net/minecraft/server/network/ServerPlayNetworkHandler
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.findRealType(MixinTargetContext.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:913)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:880)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:515)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:456)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:432)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:312)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 12 more
```

It appears that the issue is not related to any Fabric-specific fluff (I am about 99% sure).

**Comment by Mumfrey** [comment]
Ah yes, this is a straight up logic error.

The descriptor transformation logic is assuming that mixin references in the LVT are either local types of the current mixin or of a super mixin. In this case because you have a local variable of a mixin type which *isn't* in the hierarchy it's not able to resolve the relationship. This resolution needs to be a bit smarter.

You may be able to work around it for now by directly using the type-casted var instead of assigning it to a local variable first. eg. `((CustomPayloadC2SPacketAccessor)packet).getChannel()`

This is not intended, accessors mixins are supposed to have first class status so the resolution needs to be fixed.
