### ISSUE TITLE
Accessor does not detect and report staticness mismatch for target members, causing cryptic VerifyError

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#341]
I get the following error:
```
[02:26:16] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/multiplayer/ChunkProviderClient.getBlankChunk_$md$f13732$0()Lnet/minecraft/world/chunk/Chunk; @0: aload_0
  Reason:
    Type top (current frame, locals[0]) is not assignable to reference type
  Current Frame:
    bci: @0
    flags: { }
    locals: { }
    stack: { }
  Bytecode:
    0x0000000: 2ab4 002f b0                           

	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
	at net.minecraft.util.Util.runTask(Util.java:54) [Util.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1165) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:437) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/multiplayer/ChunkProviderClient.getBlankChunk_$md$f13732$0()Lnet/minecraft/world/chunk/Chunk; @0: aload_0
  Reason:
    Type top (current frame, locals[0]) is not assignable to reference type
  Current Frame:
    bci: @0
    flags: { }
    locals: { }
    stack: { }
  Bytecode:
    0x0000000: 2ab4 002f b0                           

	at net.minecraft.client.multiplayer.WorldClient.createChunkProvider(WorldClient.java:131) ~[WorldClient.class:?]
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:77) ~[WorldClient.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleJoinGame(NetHandlerPlayClient.java:324) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.processPacket(SPacketJoinGame.java:89) ~[SPacketJoinGame.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.processPacket(SPacketJoinGame.java:13) ~[SPacketJoinGame.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_212]
	at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
	... 15 more
```
With this mixin:
```java
package io.github.opencubicchunks.cubicchunks.core.asm.mixin.core.client;

import it.unimi.dsi.fastutil.longs.Long2ObjectMap;
import net.minecraft.client.multiplayer.ChunkProviderClient;
import net.minecraft.world.chunk.Chunk;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.gen.Accessor;

@Mixin(ChunkProviderClient.class)
public interface IChunkProviderClient {
    @Accessor static Chunk getBlankChunk() {
        throw new Error("IChunkProviderClient failed to apply");
    }

    @Accessor Long2ObjectMap<Chunk> getChunkMapping();
}
```

**Comment by Mumfrey** [comment]
This is happening because the field you are trying to access is not static but your accessor method is. I can have Mixin throw a more descriptive error in this situation but there's obviously no way to fix it since there's no way to access an instance member with no instance.

To fix the issue, remove the `static` modifier from the `@Accessor` method.

I will have Mixin detect this situation and emit an error instead of triggering the VerifyError.

**Comment by Barteks2x** [comment]
I'm blind, I was 100% sure this is static.
