### ISSUE TITLE
Legacy Forge crash in 0.8

### ISSUE THREAD

**Issue by RoccoDev** [SpongePowered/Mixin#360]
With 0.8, Minecraft crashes when trying to load Mixin in a Forge environment.

(Minecraft 1.12.2)

Error:
```
18:15:32] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:15:32] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:15:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:15:32] [main/INFO] [FML]: Forge Mod Loader version 14.23.3.2655 for Minecraft 1.12.2 loading
[18:15:32] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_201, running on Linux:amd64:5.0.9-301.fc30.x86_64, installed at /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-6.fc30.x86_64/jre
[18:15:32] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from 5zig-Reborn-1.12.2-3.13.0.jar
[18:15:32] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:15:32] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[18:15:32] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8-preview Source=file:/home/roccodev/MultiMC/instances/1.12.2/minecraft/mods/5zig-Reborn-1.12.2-3.13.0.jar Service=LaunchWrapper Env=CLIENT
[18:15:32] [main/WARN] [mixin]: Error cleaning class output directory: .mixin.out/class: failed to delete one or more files; see suppressed exceptions for details
[18:15:32] [main/ERROR] [mixin]: Catching
java.lang.NullPointerException: null
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.initFMLCoreMod(MixinPlatformAgentFMLLegacy.java:167) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.accept(MixinPlatformAgentFMLLegacy.java:149) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinContainer.<init>(MixinContainer.java:72) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:137) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:129) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.init(MixinPlatformManager.java:98) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.launch.MixinBootstrap.getPlatform(MixinBootstrap.java:112) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:159) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:46) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_201]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[18:15:32] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:15:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:15:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:15:32] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[18:15:32] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[18:15:32] [main/ERROR] [mixin]: Mixin config mixins.json does not specify "minVersion" property
[18:15:32] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@696da30b
[18:15:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:15:34] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[18:15:34] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[18:15:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:15:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:15:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:15:34] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[18:15:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:15:34] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[18:15:34] [main/FATAL] [mixin]: Mixin prepare failed preparing MixinCommonMinecraft in mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException java.lang.IllegalArgumentException
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: java.lang.IllegalArgumentException
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:800) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:685) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:618) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:487) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:412) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:388) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:287) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:159) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:146) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [5zig-Reborn-1.12.2-3.13.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.tree.ClassNode.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$MixinClassNode.<init>(MixinInfo.java:142) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$MixinClassNode.<init>(MixinInfo.java:137) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.createClassNode(MixinInfo.java:280) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.connect(MixinInfo.java:227) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.<init>(MixinInfo.java:222) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.<init>(MixinInfo.java:217) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:794) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	... 25 more
[18:15:34] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.json:MixinCommonMinecraft] from phase [DEFAULT] in config [mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:620) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:569) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:490) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:412) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:388) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:287) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:159) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:146) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: java.lang.IllegalArgumentException
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:800) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:685) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:618) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:487) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:412) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:388) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:287) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:159) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:146) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 14 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.tree.ClassNode.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$MixinClassNode.<init>(MixinInfo.java:142) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$MixinClassNode.<init>(MixinInfo.java:137) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.createClassNode(MixinInfo.java:280) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.connect(MixinInfo.java:227) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.<init>(MixinInfo.java:222) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.<init>(MixinInfo.java:217) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:794) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:685) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:618) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:487) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:412) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:388) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:287) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:159) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:146) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[5zig-Reborn-1.12.2-3.13.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 14 more
```
The manifest:
```
Manifest-Version: 1.0
TweakOrder: -900
MixinConfigs: mixins.json
TweakClass: org.spongepowered.asm.launch.MixinTweaker
```
Works fine in vanilla and on 0.7.11.

**Comment by Mumfrey** [comment]
ASM 6.2 is required for 0.8, looks like you're still trying to run with 5.2.

**Comment by Mumfrey** [comment]
I do see where the other error is coming from though, I will fix that.
