### ISSUE TITLE
Bumping Mixin to 0.8 makes reobfJar fail

### ISSUE THREAD

**Issue by RDIL** [SpongePowered/Mixin#367]
In my project, I tried to bump Mixin from 0.7.11 to 0.8 ([pr](https://github.com/hyperiumjailbreak/client/pull/194)), and it now fails the CI build and local build.

After turning debugging on in Gradle, I got the full stacktrace, which can be found [here](https://hasteb.in/yagosaka.kotlin).

The part that mainly caught my attention was this part:
```java
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:228)
	at net.md_5.specialsource.JarRemapper.remapJar(JarRemapper.java:189)
	at net.minecraftforge.gradle.user.TaskSingleReobf.applySpecialSource(TaskSingleReobf.java:235)
	at net.minecraftforge.gradle.user.TaskSingleReobf.doTask(TaskSingleReobf.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 114 more
```
because it looks like the cause is an illegal argument to a ASM `ClassReader` constructor.

Since ASM was updated in 0.8's preview, I would assume the failures and changes may be the cause.

@liach tried helping (for which I'm grateful), but I think I need a third eye to determine if this is just me or if this is indeed Mixin or MixinGradle messing up.

Thank you!

**Comment by RDIL** [comment]
@Mumfrey any reason why this is invalid?

**Comment by liach** [comment]
This is not related to mixin and since this is not an official distribution from the sponge maven, the issue is not supported.

**Comment by Mumfrey** [comment]
Mixin 0.8 is not released. MixinGradle for 0.8 is not even *available*. You're reporting something from an unsupported environment and the error isn't even in Mixin, it's because you have your build environment incorrectly configured and this isn't an "I don't know how to use gradle" daycare.

**Comment by RDIL** [comment]
Okay I’ll wait for official releases

**Comment by RDIL** [comment]
Okay, I understand now.  Sorry for the trouble.
