### ISSUE TITLE
AnalyzerException: Error at instruction 8: Insufficient maximum stack size with -Dmixin.debug.verbose=true on ModifyConstant

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/Mixin#368]
I get this exception:
```
[00:49:44] [Client thread/ERROR] [mixin]: Catching
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 8: Insufficient maximum stack size.
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:298) ~[asm-debug-all-5.2.jar:5.2]
	at org.spongepowered.asm.mixin.injection.invoke.util.InsnFinder.findPopInsn(InsnFinder.java:164) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyConstantInjector.checkNarrowing(ModifyConstantInjector.java:145) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyConstantInjector.injectConstantModifier(ModifyConstantInjector.java:118) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyConstantInjector.inject(ModifyConstantInjector.java:85) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:202) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:369) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1224) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1003) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:356) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:297) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:337) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.apply(MixinProcessor.java:565) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:542) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:348) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:159) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:146) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_221]
	at io.github.opencubicchunks.cubicchunks.core.CubicChunks.preInit(CubicChunks.java:104) [CubicChunks.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639) [FMLModContainer.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:514) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:422) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
Caused by: java.lang.IndexOutOfBoundsException: Insufficient maximum stack size.
	at org.objectweb.asm.tree.analysis.Frame.push(Frame.java:237) ~[asm-debug-all-5.2.jar:5.2]
	at org.spongepowered.asm.mixin.injection.invoke.util.InsnFinder$PopAnalyzer$PopFrame.push(InsnFinder.java:120) ~[mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.invoke.util.InsnFinder$PopAnalyzer$PopFrame.push(InsnFinder.java:95) ~[mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:270) ~[asm-debug-all-5.2.jar:5.2]
	at org.spongepowered.asm.mixin.injection.invoke.util.InsnFinder$PopAnalyzer$PopFrame.execute(InsnFinder.java:109) ~[mixin-0.8-preview-SNAPSHOT.jar:0.8-preview-SNAPSHOT+unknown-b0.git-unknown]
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:200) ~[asm-debug-all-5.2.jar:5.2]
	... 69 more
```
The simplest test case is the following target class:
```java
public class TestTarget {
    public boolean test() {
        int i = 10;
        return i >= 0;
    }
}
```

And the following mixin:
```java
@Mixin(TestTarget.class)
public class TestMixin {
    @ModifyConstant(method = "test", constant = @Constant(intValue = 0, expandZeroConditions = Constant.Condition.GREATER_THAN_OR_EQUAL_TO_ZERO))
    private int testMixin(int val) {
        return val;
    }
}
```

**Comment by Mumfrey** [comment]
Ok I see what the problem is. This is kind of a symptom of something that some injectors handle in a fairly ugly way so while there is a simple fix, I think I'm going to take the opportunity to fix this properly with a solution which should hopefully get rid of this *class* of problem once and for all.

Thanks for the concise report, I will fix this.
