### ISSUE TITLE
Static Field Accessor interface is a mixin class and cannot be referenced directly

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#376]
Testing Mixin 0.8 on Sponge:

Basically put, what I thought was a chicken and egg situation of an Accessor mixin not being transformed, ended up being the accessor mixin itself being missed in the config file. The error was very unhelpful.

#### Original issue

Using the [following Static Field Accessor](https://github.com/SpongePowered/SpongeCommon/blob/2f8b976b2e8e618c4c3052869db42bfbddbb25ec/src/main/java/org/spongepowered/common/mixin/core/advancements/AdvancementManagerAccessor.java#L36) in client [code that it itself is not a Mixin](https://github.com/SpongePowered/SpongeCommon/blob/2f8b976b2e8e618c4c3052869db42bfbddbb25ec/src/main/java/org/spongepowered/common/registry/type/advancement/AdvancementRegistryModule.java#L70) results in an exception about Mixing not being referenced directly.

The exception [as seen in a Unit test](https://github.com/SpongePowered/SpongeCommon/blob/2f8b976b2e8e618c4c3052869db42bfbddbb25ec/src/main/java/org/spongepowered/common/registry/type/advancement/AdvancementRegistryModule.java?fbclid=IwAR1mT4HSwyPTdKgfmhXIposMXA4KO1ZpRp2pFrv8H-ZcXsijwkQc3c_hZP0#L70) looks like so:

```
    [20:41:22] [Test worker/ERROR]: Unable to launch
    java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at org.spongepowered.lwts.runner.LaunchWrapperTestRunner.loadTestClass(LaunchWrapperTestRunner.java:79) [lwts-1.0.0.jar:?]
        at org.spongepowered.lwts.runner.LaunchWrapperParameterized.<init>(LaunchWrapperParameterized.java:45) [lwts-1.0.0.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_231]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_231]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_231]
        at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104) [junit-4.12.jar:4.12]
        at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86) [junit-4.12.jar:4.12]
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [junit-4.12.jar:4.12]
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26) [junit-4.12.jar:4.12]
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [junit-4.12.jar:4.12]
        at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33) [junit-4.12.jar:4.12]
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:78) [gradle-testing-jvm-4.10.3.jar:4.10.3]
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58) [gradle-testing-jvm-4.10.3.jar:4.10.3]
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38) [gradle-testing-jvm-4.10.3.jar:4.10.3]
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66) [gradle-testing-jvm-4.10.3.jar:4.10.3]
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51) [gradle-testing-base-4.10.3.jar:4.10.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-4.10.3.jar:4.10.3]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-4.10.3.jar:4.10.3]
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32) [gradle-messaging-4.10.3.jar:4.10.3]
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93) [gradle-messaging-4.10.3.jar:4.10.3]
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source) [?:?]
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117) [gradle-testing-base-4.10.3.jar:4.10.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-4.10.3.jar:4.10.3]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-4.10.3.jar:4.10.3]
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155) [gradle-messaging-4.10.3.jar:4.10.3]
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137) [gradle-messaging-4.10.3.jar:4.10.3]
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404) [gradle-messaging-4.10.3.jar:4.10.3]
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) [gradle-base-services-4.10.3.jar:4.10.3]
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) [gradle-base-services-4.10.3.jar:4.10.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) [gradle-base-services-4.10.3.jar:4.10.3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
    Caused by: java.lang.NoClassDefFoundError: org/spongepowered/common/mixin/core/advancements/AdvancementListAccessor
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_231]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_231]
        at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_231]
        at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_231]
        at org.spongepowered.common.registry.util.RegistryModuleLoader.getCustomRegistration(RegistryModuleLoader.java:88) ~[RegistryModuleLoader.class:?]
        at org.spongepowered.common.registry.util.RegistryModuleLoader.tryModulePhaseRegistration(RegistryModuleLoader.java:55) ~[RegistryModuleLoader.class:?]
        at org.spongepowered.common.registry.SpongeGameRegistry.registerModulePhase(SpongeGameRegistry.java:244) ~[SpongeGameRegistry.class:?]
        at org.spongepowered.common.registry.SpongeGameRegistry.preRegistryInit(SpongeGameRegistry.java:171) ~[SpongeGameRegistry.class:?]
        at org.spongepowered.common.test.TestMain.main(TestMain.java:43) ~[TestMain.class:?]
        ... 48 more
    Caused by: java.lang.ClassNotFoundException: org.spongepowered.common.mixin.core.advancements.AdvancementListAccessor
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_231]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_231]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_231]
        at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_231]
        at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_231]
        at org.spongepowered.common.registry.util.RegistryModuleLoader.getCustomRegistration(RegistryModuleLoader.java:88) ~[RegistryModuleLoader.class:?]
        at org.spongepowered.common.registry.util.RegistryModuleLoader.tryModulePhaseRegistration(RegistryModuleLoader.java:55) ~[RegistryModuleLoader.class:?]
        at org.spongepowered.common.registry.SpongeGameRegistry.registerModulePhase(SpongeGameRegistry.java:244) ~[SpongeGameRegistry.class:?]
        at org.spongepowered.common.registry.SpongeGameRegistry.preRegistryInit(SpongeGameRegistry.java:171) ~[SpongeGameRegistry.class:?]
        at org.spongepowered.common.test.TestMain.main(TestMain.java:43) ~[TestMain.class:?]
        ... 48 more
    Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:357) ~[mixin-0.8-SNAPSHOT.jar:0.8-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[mixin-0.8-SNAPSHOT.jar:0.8-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[mixin-0.8-SNAPSHOT.jar:0.8-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[mixin-0.8-SNAPSHOT.jar:0.8-SNAPSHOT+unknown-b0.git-unknown]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_231]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_231]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_231]
        at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_231]
        at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_231]
        at org.spongepowered.common.registry.util.RegistryModuleLoader.getCustomRegistration(RegistryModuleLoader.java:88) ~[RegistryModuleLoader.class:?]
        at org.spongepowered.common.registry.util.RegistryModuleLoader.tryModulePhaseRegistration(RegistryModuleLoader.java:55) ~[RegistryModuleLoader.class:?]
        at org.spongepowered.common.registry.SpongeGameRegistry.registerModulePhase(SpongeGameRegistry.java:244) ~[SpongeGameRegistry.class:?]
        at org.spongepowered.common.registry.SpongeGameRegistry.preRegistryInit(SpongeGameRegistry.java:171) ~[SpongeGameRegistry.class:?]
        at org.spongepowered.common.test.TestMain.main(TestMain.java:43) ~[TestMain.class:?]
        ... 48 more
    Caused by: java.lang.NoClassDefFoundError: org.spongepowered.common.mixin.core.advancements.AdvancementListAccessor is a mixin class and cannot be referenced directly
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:322) ~[mixin-0.8-SNAPSHOT.jar:0.8-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[mixin-0.8-SNAPSHOT.jar:0.8-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[mixin-0.8-SNAPSHOT.jar:0.8-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[mixin-0.8-SNAPSHOT.jar:0.8-SNAPSHOT+unknown-b0.git-unknown]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_231]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_231]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_231]
        at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_231]
        at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_231]
        at org.spongepowered.common.registry.util.RegistryModuleLoader.getCustomRegistration(RegistryModuleLoader.java:88) ~[RegistryModuleLoader.class:?]
        at org.spongepowered.common.registry.util.RegistryModuleLoader.tryModulePhaseRegistration(RegistryModuleLoader.java:55) ~[RegistryModuleLoader.class:?]
        at org.spongepowered.common.registry.SpongeGameRegistry.registerModulePhase(SpongeGameRegistry.java:244) ~[SpongeGameRegistry.class:?]
        at org.spongepowered.common.registry.SpongeGameRegistry.preRegistryInit(SpongeGameRegistry.java:171) ~[SpongeGameRegistry.class:?]
        at org.spongepowered.common.test.TestMain.main(TestMain.java:43) ~[TestMain.class:?]
        ... 48 more

```

While other cases are being transformed fine when the interface/method is being accessed in a non static context.

**Comment by gabizou** [comment]
So, looking further into it, the original accessor was just fine, but it was a [change of the signature from AdvancementListBridge to Accessor](https://github.com/SpongePowered/SpongeCommon/commit/e78f0abf75a9f3b5167b82931d3f0dcbc627df63#diff-ce956b3a9a1b616f8227ceefeb635a5aL34-R48) that's now being thrown. What's interesting is that it's not even the fact that the method signature contains the accessor mixin, but simply the accessor mixin itself being referenced for some reason in client code is throwing a hissy fit. Now, I can say that the game launches fine in development, but just not in unit testing in this particular case.

**Comment by gabizou** [comment]
So, looking even further into it, the mixin class is in fact being classloaded and transformed and decompiled by fernflower to appropriately have the correct static mixin:

```
package org.spongepowered.common.mixin.core.advancements;

import net.minecraft.advancements.AdvancementList;
import net.minecraft.advancements.AdvancementManager;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.gen.Accessor;
import org.spongepowered.asm.mixin.transformer.meta.MixinProxy;

@Mixin({AdvancementManager.class})
public interface AdvancementManagerAccessor {
    // $FF: synthetic method
    @Final
    @Accessor("ADVANCEMENT_LIST")
    @MixinProxy(
        sessionId = "9a2abae9-e875-4fba-833c-eef958e99221"
    )
    static AdvancementList accessor$getAdvancementList() {
        return AdvancementManager.accessor$getAdvancementList_$md$e99221$0();
    }
}
```
And, even when the target class is requested to be classloaded first (to avoid a chicken and the egg situation), the accessor is simply not allowed to be used in client code.... Why? I don't know at this point, but I was absolutely sure this was working in 0.7 for a while now.

**Comment by Mumfrey** [comment]
I'm unable to reproduce this, can you confirm the branch you're using and what settings to launch gradle with?
