### ISSUE TITLE
NPE when using array clone method in mixin

### ISSUE THREAD

**Issue by Earthcomputer** [SpongePowered/Mixin#383]
I tried to use the `clone()` method on a double array (`double[]`) inside a mixin, and I got the following error:
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [worldgentests.mixins.json:MixinNoiseGeneratorOctaves] from phase [DEFAULT] in config [worldgentests.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 20 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded NullPointerException whilst transforming the mixin class: [MAIN Applicator Phase -> worldgentests.mixins.json:MixinNoiseGeneratorOctaves -> Apply Methods -> ([DDDDIIIDDD)[D:func_807_a -> Transform Instructions -> INVOKEVIRTUAL [D::clone()Ljava/lang/Object;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:490)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:523)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethodRef(MixinTargetContext.java:572)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:464)
	... 27 more
```
I am pretty sure I didn't mess anything else up, as this happened inside an `@Overwrite`.

**Comment by Mumfrey** [comment]
Ah ok I'll take a look into that.
