### ISSUE TITLE
Static Accessor/Invoker Mixins cannot be accessed from other Mixin injections

### ISSUE THREAD

**Issue by js6pak** [SpongePowered/Mixin#389]
Basically same as #305 but static

```java
@Mixin(Minecraft.class)
public interface MinecraftAccessor {
    @Accessor(value = "theMinecraft")
    static Minecraft getInstance() {
        throw new UnsupportedOperationException();
    }
}
```
Accessing `MinecraftAccessor.getInstance()` works from normal (non mixin) classes, but not from other mixin classes like
```java
@Mixin(GuiMainMenu.class)
public class MixinGuiMainMenu {
    @Inject(method = "initGui", at = @At("RETURN"))
    private void onInitGui(CallbackInfo ci) {
        System.out.println(MinecraftAccessor.getInstance());
    }
}
```
throws 
```
Exception in thread "Minecraft main thread" java.lang.NoSuchMethodError: net.earthcomputer.examplemod.mixin.MinecraftAccessor.getInstance_$md$f2453a$0()Lnet/minecraft/client/Minecraft;
	at net.minecraft.src.GuiMainMenu.handler$zza000$onInitGui(GuiMainMenu.java:517)
	at net.minecraft.src.GuiMainMenu.initGui(GuiMainMenu.java:74)
	at net.minecraft.src.GuiScreen.setWorldAndResolution(GuiScreen.java:85)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:412)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:300)
	at net.minecraft.client.Minecraft.run(Minecraft.java:480)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Johni0702** [comment]
Is this with stock Mixin 0.8?

I ran into a similar issue with Fabric's Mixin fork but wasn't able to reproduce it with stock Mixin in the same environment: https://github.com/FabricMC/Mixin/issues/28

**Comment by gabizou** [comment]
Please provide the following:
- Mixin version used (exactly which version, you can find the build info from the MANIFEST.MF file in the mixing library)
- Output of the accessor mixin (and logs!) by using `-Dmixin.debug.export=true` and uploading the `.mixin.out` folder that's generated after loading.

**Comment by Mumfrey** [comment]
Confirmed, I can't reproduce this. Can you please let me know the exact mixin version you are using and/or which fork if you're not using official builds?

**Comment by js6pak** [comment]
Yeah, sorry for that. I forgot I was using fabric's fork. Next time I will check stock mixin before creating issue here. (and yes its https://github.com/FabricMC/Mixin/issues/28)
