### ISSUE TITLE
Injector fails with cryptic error if you forget to add arguments to handler method

### ISSUE THREAD

**Issue by Proximyst** [SpongePowered/Mixin#411]
This was discovered using FabricMC's fork: https://github.com/FabricMC/Mixin

Given the following code:
```java
  @ModifyVariable(
      method = "move",
      slice = @Slice(
          from = @At(
              value = "INVOKE",
              target = "Lnet/minecraft/world/World;setBlockEntity(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/entity/BlockEntity;)V"
          )
      ),
      at = @At(
          value = "LOAD",
          ordinal = 2
      ),
      require = 1,
      print = true
  )
  public BlockState loadBlockState(/* BlockState $ignored */) {
    return ...;
  }
```
the injector will fail with the following stacktrace. This is due to having no arguments, and should (according to Mumfrey on Discord) have a proper error message instead.

```

/*****************************************************************************************************************/
--
  | /*         Target Class : net.minecraft.class_2665                                                               */
  | /*        Target Method : method_11481                                                                           */
  | /*        Callback Name : loadBlockState                                                                         */
  | /*         Capture Type : class_2680                                                                             */
  | /*          Instruction : [10] VarInsnNode ALOAD                                                                 */
  | /*****************************************************************************************************************/
  | /*           Match mode : IMPLICIT (match single)                                                                */
  | /*        Match ordinal : any                                                                                    */
  | /*          Match index : any                                                                                    */
  | /*        Match name(s) : any                                                                                    */
  | /*            Args only : false                                                                                  */
  | /*****************************************************************************************************************/
  | /* INDEX  ORDINAL                            TYPE  NAME                                                CANDIDATE */
  | /* [  1]    [  0]                      class_1937  ☃                                                   -         */
  | /* [  2]    [  0]                      class_2338  ☃                                                   -         */
  | /* [  3]    [  0]                      class_2350  ☃                                                   -         */
  | /* [  4]    [  0]                         boolean  ☃                                                   -         */
  | /* [  5]    [  1]                      class_2338  ☃                                                   -         */
  | /* [  6]                                        -                                                                */
  | /* [  7]                                        -                                                                */
  | /* [  8]                                        -                                                                */
  | /* [  9]                                        -                                                                */
  | /* [ 10]                                        -                                                                */
  | /* [ 11]                                        -                                                                */
  | /* [ 12]                                        -                                                                */
  | /* [ 13]                                        -                                                                */
  | /* [ 14]                                        -                                                                */
  | /* [ 15]                                        -                                                                */
  | /* [ 16]                                        -                                                                */
  | /* [ 17]                                        -                                                                */
  | /* [ 18]                                        -                                                                */
  | /* [ 19]                                        -                                                                */
  | /* [ 20]                                        -                                                                */
  | /* [ 21]                                        -                                                                */
  | /* [ 22]                                        -                                                                */
  | /* [ 23]                                        -                                                                */
  | /* [ 24]                                        -                                                                */
  | /*****************************************************************************************************************/
  | [22:14:15] [main/FATAL]: Mixin apply failed katarina.mixins.json:bugfix.pistons.PistonBlockMixin -> net.minecraft.class_2665: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded ArrayIndexOutOfBoundsException whilst transforming the mixin class: [INJECT Applicator Phase -> katarina.mixins.json:bugfix.pistons.PistonBlockMixin -> Apply Injections -> Inject -> katarina.mixins.json:bugfix.pistons.PistonBlockMixin->@ModifyVariable::loadBlockState()Lnet/minecraft/class_2680;]
  | org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ArrayIndexOutOfBoundsException whilst transforming the mixin class: [INJECT Applicator Phase -> katarina.mixins.json:bugfix.pistons.PistonBlockMixin -> Apply Injections -> Inject -> katarina.mixins.json:bugfix.pistons.PistonBlockMixin->@ModifyVariable::loadBlockState()Lnet/minecraft/class_2680;]
  | at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1289) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
  | at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
  | at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) ~[fabric-server-launch.jar:?]
  | at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
  | at net.minecraft.class_2378.method_10237(class_2378.java:169) ~[intermediary-server.jar:?]
  | at net.minecraft.class_2378.method_29110(class_2378.java:220) ~[intermediary-server.jar:?]
  | at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) [?:?]
  | at net.minecraft.class_2378.<clinit>(class_2378.java:219) [intermediary-server.jar:?]
  | at net.minecraft.class_2966.method_12851(class_2966.java:41) [intermediary-server.jar:?]
  | at net.minecraft.server.Main.main(Main.java:89) [intermediary-server.jar:?]
  | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
  | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
  | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
  | at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
  | at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
  | at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
  | at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
  | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
  | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
  | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
  | at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
  | Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
  | at org.spongepowered.asm.mixin.injection.code.Injector.checkCoerce(Injector.java:576) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.injection.code.Injector.validateParams(Injector.java:531) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:153) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:377) ~[fabric-server-launch.jar:?]
  | at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1273) ~[fabric-server-launch.jar:?]
  | ... 32 more
  | org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [katarina.mixins.json:bugfix.pistons.PistonBlockMixin] from phase [DEFAULT] in config [katarina.mixins.json] FAILED during APPLY
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
  | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
  | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
  | at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
  | at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
  | at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  | at net.minecraft.class_2378.method_10237(class_2378.java:169)
  | at net.minecraft.class_2378.method_29110(class_2378.java:220)
  | at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
  | at net.minecraft.class_2378.<clinit>(class_2378.java:219)
  | at net.minecraft.class_2966.method_12851(class_2966.java:41)
  | at net.minecraft.server.Main.main(Main.java:89)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  | at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
  | at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
  | at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
  | Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ArrayIndexOutOfBoundsException whilst transforming the mixin class: [INJECT Applicator Phase -> katarina.mixins.json:bugfix.pistons.PistonBlockMixin -> Apply Injections -> Inject -> katarina.mixins.json:bugfix.pistons.PistonBlockMixin->@ModifyVariable::loadBlockState()Lnet/minecraft/class_2680;]
  | at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1289)
  | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
  | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
  | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
  | at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
  | ... 26 more
  | Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
  | at org.spongepowered.asm.mixin.injection.code.Injector.checkCoerce(Injector.java:576)
  | at org.spongepowered.asm.mixin.injection.code.Injector.validateParams(Injector.java:531)
  | at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:153)
  | at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
  | at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:377)
  | at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1273)
  | ... 32 more
  | Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
  | Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
  | Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
  | ... 1 more
  | Caused by: java.lang.reflect.InvocationTargetException
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  | at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
  | ... 2 more
  | Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  | at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
  | at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
  | at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
  | ... 7 more
  | Caused by: java.lang.reflect.InvocationTargetException
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  | at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
  | ... 9 more
  | Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
  | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
  | at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
  | at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
  | at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
  | at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  | at net.minecraft.class_2378.method_10237(class_2378.java:169)
  | at net.minecraft.class_2378.method_29110(class_2378.java:220)
  | at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
  | at net.minecraft.class_2378.<clinit>(class_2378.java:219)
  | at net.minecraft.class_2966.method_12851(class_2966.java:41)
  | at net.minecraft.server.Main.main(Main.java:89)
  | ... 14 more
  | Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [katarina.mixins.json:bugfix.pistons.PistonBlockMixin] from phase [DEFAULT] in config [katarina.mixins.json] FAILED during APPLY
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
  | ... 26 more
  | Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ArrayIndexOutOfBoundsException whilst transforming the mixin class: [INJECT Applicator Phase -> katarina.mixins.json:bugfix.pistons.PistonBlockMixin -> Apply Injections -> Inject -> katarina.mixins.json:bugfix.pistons.PistonBlockMixin->@ModifyVariable::loadBlockState()Lnet/minecraft/class_2680;]
  | at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1289)
  | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
  | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
  | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
  | at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
  | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
  | ... 26 more
  | Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
  | at org.spongepowered.asm.mixin.injection.code.Injector.checkCoerce(Injector.java:576)
  | at org.spongepowered.asm.mixin.injection.code.Injector.validateParams(Injector.java:531)
  | at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:153)
  | at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
  | at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:377)
  | at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1273)
  | ... 32 more
```

**Comment by Mumfrey** [comment]
Thanks for opening an issue, this should be able to be rolled up with the next round of triage.

**Comment by Barteks2x** [comment]
Similar issue happens if you "forget" to add an argument to a redirect method (index out of bounds in checkCoerce), but with redirect (this happened to me when updating to 1.16 and vanilla has an extra argument on a method).

**Comment by yyny** [comment]
This is the critical trace from my debug build:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at org.spongepowered.asm.mixin.injection.code.Injector.checkCoerce(Injector.java:576) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
        at org.spongepowered.asm.mixin.injection.code.Injector.validateParams(Injector.java:531) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
        at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:155) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
        at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
        ... 23 more
```
