### ISSUE TITLE
Invalid access flags error when mixing in on a class with inner class

### ISSUE THREAD

**Issue by jk-5** [SpongePowered/Mixin#45]
I'm writing a mixin for BiomeGenBase, similar as in sponge common. Applying of this mixin fails with:

```
[21:25:59] [Server thread/INFO] [mixin]: Mixing world.MixinBiomeGenBase into net.minecraft.world.biome.BiomeGenBase
[21:28:05] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/world/biome/BiomeGenBase
    at nl.jk_5.pumpkin.server.registry.PumpkinGameRegistry.setBiomeTypes(PumpkinGameRegistry.java:183) ~[PumpkinGameRegistry.class:?]
    at nl.jk_5.pumpkin.server.registry.PumpkinGameRegistry.init(PumpkinGameRegistry.java:441) ~[PumpkinGameRegistry.class:?]
    at nl.jk_5.pumpkin.server.Pumpkin.initialize(Pumpkin.java:81) ~[Pumpkin.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.onStartServer(SourceFile:119) ~[DedicatedServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.startServer(SourceFile:93) ~[DedicatedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(SourceFile:417) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.biome.BiomeGenBase
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.MixinTransformerError: An unexpected critical error was encountered
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:372) ~[mixin-0.3.3-SNAPSHOT.jar:0.3.3-SNAPSHOT+unknown-b0.git-unknown]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:101) ~[mixin-0.3.3-SNAPSHOT.jar:0.3.3-SNAPSHOT+unknown-b0.git-unknown]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 7 more
Caused by: java.lang.IllegalArgumentException: Invalid access flags: 16425
    at org.objectweb.asm.util.CheckClassAdapter.checkAccess(CheckClassAdapter.java:599) ~[asm-debug-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.util.CheckClassAdapter.visitInnerClass(CheckClassAdapter.java:460) ~[asm-debug-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.tree.InnerClassNode.accept(InnerClassNode.java:99) ~[asm-debug-all-5.0.3.jar:5.0.3]
    at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:404) ~[asm-debug-all-5.0.3.jar:5.0.3]
    at org.spongepowered.asm.mixin.transformer.MixinTransformerModuleCheckClass.postApply(MixinTransformerModuleCheckClass.java:56) ~[mixin-0.3.3-SNAPSHOT.jar:0.3.3-SNAPSHOT+unknown-b0.git-unknown]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.postApply(MixinTransformer.java:560) ~[mixin-0.3.3-SNAPSHOT.jar:0.3.3-SNAPSHOT+unknown-b0.git-unknown]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:521) ~[mixin-0.3.3-SNAPSHOT.jar:0.3.3-SNAPSHOT+unknown-b0.git-unknown]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:360) ~[mixin-0.3.3-SNAPSHOT.jar:0.3.3-SNAPSHOT+unknown-b0.git-unknown]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:101) ~[mixin-0.3.3-SNAPSHOT.jar:0.3.3-SNAPSHOT+unknown-b0.git-unknown]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 7 more
```

Note that the stacktrace mentions the CheckClassAdapter's visitInnerClass. It fails with an invalid access flags error (16425). After some calculation, it turns out that the inner class has ACC_SUPER (32) where that is not allowed.

It fails on visiting inner class TempCategory in BiomeGenBase, which is an enum.

Mixin source code: http://pastebin.com/Ey52AWhG

Not sure if this is something i am overlooking or an actual issue. I'm totally out of ideas so having your vision on this would be nice.

Tried looking at the bytecode from the `-Dmixin.dumpTargetOnFailure=true` option, but it doesn't actually dump the bytecode

**Comment by jk-5** [comment]
Same error when mixing in to ServerStatusResponse$MinecraftProtocolVersionIdentifier, which also has an inner class. This inner class is public (1) and static (8), that adds op to 9 as modifier. The error tells that it's 41. 41 - 9 = 32, which also is ACC_SUPER

**Comment by Mumfrey** [comment]
Interesting, it's actually not mixin which is setting the ACC_SUPER flag, at least I don't think so, and I can't even think of a good reason that it would be disallowed on inner classes in the first place, although apparently this is the case. Are there any other transformers in play which might be setting the flag that you know of? Since we haven't run across this issue yet in Sponge.

It's no problem to have the mixin transformer strip the invalid flag, but it would be good to know where it's coming from.

The `dumpTargetOnFailure` isn't firing because that only catches actual mixin application errors (errors thrown by the mixin processor itself when it failed to apply) and doesn't catch other errors thrown by plugin modules like the validator, although it would be pretty easy to add that if it'll help you debug this issue.

**Comment by Mumfrey** [comment]
Just checked out the bytecode in vanilla and in forge and neither have the invalid flag on their inner class declaration:

**Forge**
    cw.visitInnerClass("net/minecraft/world/biome/BiomeGenBase$TempCategory", "net/minecraft/world/biome/BiomeGenBase", "TempCategory", ACC_PUBLIC + ACC_FINAL + ACC_STATIC + ACC_ENUM);
    cw.visitInnerClass("net/minecraft/world/biome/BiomeGenBase$SwitchEnumCreatureType", "net/minecraft/world/biome/BiomeGenBase", "SwitchEnumCreatureType", ACC_FINAL + ACC_STATIC);
    cw.visitInnerClass("net/minecraft/world/biome/BiomeGenBase$SpawnListEntry", "net/minecraft/world/biome/BiomeGenBase", "SpawnListEntry", ACC_PUBLIC + ACC_STATIC);
    cw.visitInnerClass("net/minecraft/world/biome/BiomeGenBase$Height", "net/minecraft/world/biome/BiomeGenBase", "Height", ACC_PUBLIC + ACC_STATIC);
    cw.visitInnerClass("net/minecraft/world/biome/BiomeGenBase$FlowerEntry", "net/minecraft/world/biome/BiomeGenBase", "FlowerEntry", ACC_PUBLIC + ACC_STATIC);
    cw.visitInnerClass("net/minecraft/block/BlockFlower$EnumFlowerType", "net/minecraft/block/BlockFlower", "EnumFlowerType", ACC_PUBLIC + ACC_FINAL + ACC_STATIC + ACC_ENUM);
    cw.visitInnerClass("net/minecraftforge/event/terraingen/BiomeEvent$GetWaterColor", "net/minecraftforge/event/terraingen/BiomeEvent", "GetWaterColor", ACC_PUBLIC + ACC_STATIC);
    cw.visitInnerClass("net/minecraftforge/event/terraingen/BiomeEvent$GetGrassColor", "net/minecraftforge/event/terraingen/BiomeEvent", "GetGrassColor", ACC_PUBLIC + ACC_STATIC);
    cw.visitInnerClass("net/minecraftforge/event/terraingen/BiomeEvent$GetFoliageColor", "net/minecraftforge/event/terraingen/BiomeEvent", "GetFoliageColor", ACC_PUBLIC + ACC_STATIC);
    cw.visitInnerClass("net/minecraft/block/BlockTallGrass$EnumType", "net/minecraft/block/BlockTallGrass", "EnumType", ACC_PUBLIC + ACC_FINAL + ACC_STATIC + ACC_ENUM);
    cw.visitInnerClass("net/minecraft/block/BlockSand$EnumType", "net/minecraft/block/BlockSand", "EnumType", ACC_PUBLIC + ACC_FINAL + ACC_STATIC + ACC_ENUM);
    cw.visitInnerClass("net/minecraft/util/WeightedRandom$Item", "net/minecraft/util/WeightedRandom", "Item", ACC_PUBLIC + ACC_STATIC);

**Vanilla**
    cw.visitInnerClass("net/minecraft/world/biome/BiomeGenBase$TempCategory", "net/minecraft/world/biome/BiomeGenBase", "TempCategory", ACC_PUBLIC + ACC_FINAL + ACC_STATIC + ACC_ENUM);
    cw.visitInnerClass("net/minecraft/world/biome/BiomeGenBase$SwitchEnumCreatureType", "net/minecraft/world/biome/BiomeGenBase", "SwitchEnumCreatureType", ACC_FINAL + ACC_STATIC);
    cw.visitInnerClass("net/minecraft/world/biome/BiomeGenBase$SpawnListEntry", "net/minecraft/world/biome/BiomeGenBase", "SpawnListEntry", ACC_PUBLIC + ACC_STATIC);
    cw.visitInnerClass("net/minecraft/world/biome/BiomeGenBase$Height", "net/minecraft/world/biome/BiomeGenBase", "Height", ACC_PUBLIC + ACC_STATIC);
    cw.visitInnerClass("net/minecraft/block/BlockFlower$EnumFlowerType", "net/minecraft/block/BlockFlower", "EnumFlowerType", ACC_PUBLIC + ACC_FINAL + ACC_STATIC + ACC_ENUM);
    cw.visitInnerClass("net/minecraft/block/BlockTallGrass$EnumType", "net/minecraft/block/BlockTallGrass", "EnumType", ACC_PUBLIC + ACC_FINAL + ACC_STATIC + ACC_ENUM);
    cw.visitInnerClass("net/minecraft/block/BlockSand$EnumType", "net/minecraft/block/BlockSand", "EnumType", ACC_PUBLIC + ACC_FINAL + ACC_STATIC + ACC_ENUM);

So something in between is definitely adding that flag. Mixin doesn't actually touch inner class data in the target class so I think it's the `CheckClassAdapter` showing up an error which is being introduced elsewhere.

**Comment by jk-5** [comment]
I did not add any other transformers in the last few days. Only change is that i updated to 0.3.3 yesterday, and now it is not working. Currently i am trying some older versions to see if and when something in mixin was changed to cause this, or if i am doing something wrong.

For the ACC_SUPER flag not being allowed on inner classes, see asm's CheckClassAdapter.visitInnerClass. That method gives a list of allowed flags.

I will have a better look at the current setup of things. I can not imagine that something at my side is derping this up, but i want to confirm that. I will report back later whether or not i was able to identify the issue.

**Comment by Mumfrey** [comment]
Yeah I understand why it's failing, but what I'm not sure of what's adding that flag, as I mentioned mixin doesn't actually touch any of those flags so it's more likely that something is adding them and it's the `CheckClassAdapter` being run in mixin which is showing up the error. Certainly nothing has changed recently which would alter this behaviour.

As I mentioned above, would it help if I altered the behaviour of the `dumpTargetOnFailure` flag to also dump the class on other failures than pure mixin ones, because I can add that easily and then you might have some more info to go on.

**Comment by jk-5** [comment]
That would indeed be nice for some more debugging on my part.

**Comment by Mumfrey** [comment]
Ok, I'll push a change shortly.

**Comment by Mumfrey** [comment]
I'm on IRC by the way if you want to discuss this any further without having to go back and forth here.

**Comment by jk-5** [comment]
This has been caused by me being lazy and using `setupDevWorkspace` instead of `setupDecompWorkspace`. Apparently ForgeGradle's deobfuscator injects those ACC_SUPER flags. When running decompiled setup, it recompiles the decompiled code, so those invalid flags are not in.

I will talk to abrar about these invalid flags. Thanks for your help on this issue.

**Comment by Mumfrey** [comment]
No problem, if it's still an issue I can have the Mixin transformer strip those flags if necessary since it's likely only the `CheckClassAdapter` which will give a monkeys'. Re-open the issue if need be.

**Comment by jk-5** [comment]
Fixed in https://github.com/ModCoderPack/MCInjector/commit/05aa80e569728813c9618da86eed8afbe11154ea

**Comment by Mumfrey** [comment]
Nice :)
