### ISSUE TITLE
ClassNotFoundException with modlauncher

### ISSUE THREAD

**Issue by IzzelAliz** [SpongePowered/Mixin#458]
Logs:
<details>
<pre>
[15Jan2021 16:13:23.486] [Server thread/TRACE] [mixin/CATCHING]: Catching
java.lang.ClassNotFoundException: null
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:142) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$8(LaunchPluginHandler.java:97) ~[modlauncher-8.0.6.jar:?]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:214) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:202) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1843) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forType(ClassInfo.java:1897) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.util.asm.MixinVerifier.isAssignableFrom(MixinVerifier.java:97) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:207) ~[asm-analysis-7.2.jar:7.2]
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:400) ~[asm-analysis-7.2.jar:7.2]
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:43) ~[asm-analysis-7.2.jar:7.2]
	at org.objectweb.asm.tree.analysis.Frame.executeInvokeInsn(Frame.java:648) ~[asm-analysis-7.2.jar:7.2]
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:573) ~[asm-analysis-7.2.jar:7.2]
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:187) ~[asm-analysis-7.2.jar:7.2]
	at org.spongepowered.asm.util.Locals.generateLocalVariableTable(Locals.java:394) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.util.Locals.getGeneratedLocalVariableTable(Locals.java:363) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:317) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:287) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:250) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:429) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.6.jar:8.0.6+85+master.325de55]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_221]
	at net.minecraft.world.chunk.storage.IOWorker.<init>(SourceFile:64) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkLoader.<init>(SourceFile:29) ~[?:?]
	at net.minecraft.world.server.ChunkManager.<init>(ChunkManagerMixin.java:125) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.<init>(ServerChunkProviderMixin.java:88) ~[?:?]
	at net.minecraft.world.server.ServerWorld.<init>(ServerWorldMixin.java:184) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:335) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1857) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
[15Jan2021 16:13:23.487] [Server thread/WARN] [mixin/]: Error loading class: java/io/DataInput (java.lang.ClassNotFoundException: null)
[15Jan2021 16:13:23.487] [Server thread/TRACE] [mixin/]: Added class metadata for java/io/DataInput to metadata cache
</pre>
</details>

https://github.com/SpongePowered/Mixin/blob/4585277f9f4b026065ce749f279ea1ad4919c4f1/src/main/java/org/spongepowered/asm/mixin/transformer/ClassInfo.java#L1837-L1847

Here passes the internal name of class which passes the [package filter test](https://github.com/cpw/modlauncher/blob/3cf110cd0b2a5bcd8a44057fd0513e38a4b06f97/src/main/java/cpw/mods/modlauncher/TransformingClassLoader.java#L53-L55).

**Comment by Mumfrey** [comment]
I need to have a look into this because the bytecode provider does have failover to the context classloader so if it still fails it's because those class bytes aren't available at all, possibly because they're in the bootstrap classloader but I need to investigate.

**Comment by Mumfrey** [comment]
Closing since no further information. Please re-open if you are able to provide the requested information.
