### ISSUE TITLE
Modpack crashed

### ISSUE THREAD

**Issue by einfachmarci** [SpongePowered/Mixin#466]
[16:00:32] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:00:32] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:00:32] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:00:32] [main/INFO]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[16:00:32] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_251, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_251
[16:00:32] [main/WARN]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[16:00:32] [main/WARN]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[16:00:32] [main/INFO]: Searching C:\Users\Marcel\AppData\Roaming\.technic\modpacks\gezuschten-cooles-modpack\mods for mods
[16:00:32] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:00:32] [main/WARN]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[16:00:32] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from More-Planets-1.12.2-2.2.1-GC280.jar
[16:00:32] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F5.jar
[16:00:32] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from SteveKunG's-Lib-1.12.2-1.1.9-deobf.jar
[16:00:32] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from SteveKunG's-Lib-1.12.2-1.1.9.jar
[16:00:32] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Xaeros_Minimap_20.12.1_Forge_1.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:00:32] [main/WARN]: The coremod LoadingPlugin (xaero.common.core.LoadingPlugin) is not signed!
[16:00:32] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:00:32] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[16:00:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Marcel/AppData/Roaming/.technic/modpacks/gezuschten-cooles-modpack/mods/More-Planets-1.12.2-2.2.1-GC280.jar Service=LaunchWrapper Env=CLIENT
[16:00:33] [main/DEBUG]: Instantiating coremod class SteveKunGLibPlugin
[16:00:33] [main/INFO]: Initializing SteveKunG's Lib plugin!
[16:00:33] [main/INFO]: Compatibility level set to JAVA_8
[16:00:33] [main/DEBUG]: The coremod stevekung.mods.stevekunglib.core.SteveKunGLibPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[16:00:33] [main/WARN]: The coremod SteveKunGLibPlugin (stevekung.mods.stevekunglib.core.SteveKunGLibPlugin) is not signed!
[16:00:33] [main/DEBUG]: Enqueued coremod SteveKunGLibPlugin
[16:00:33] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[16:00:33] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:00:33] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:00:33] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:00:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:00:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:00:33] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[16:00:33] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[16:00:33] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[16:00:33] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[16:00:33] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\Marcel\AppData\Roaming\.technic\modpacks\gezuschten-cooles-modpack\mods\OptiFine_1.12.2_HD_U_F5.jar
[16:00:33] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:00:33] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[16:00:33] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[16:00:33] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[16:00:33] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[16:00:33] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[16:00:33] [main/DEBUG]: Injection complete
[16:00:33] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[16:00:33] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[16:00:34] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:00:34] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[16:00:34] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[16:00:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:00:34] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[16:00:34] [main/DEBUG]: Injection complete
[16:00:34] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[16:00:34] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[16:00:34] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[16:00:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:00:34] [main/DEBUG]: Injecting coremod MicdoodlePlugin \{micdoodle8.mods.miccore.MicdoodlePlugin\} class transformers
[16:00:34] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:99]: Successfully Registered Transformer
[16:00:34] [main/TRACE]: Registering transformer micdoodle8.mods.miccore.MicdoodleTransformer
[16:00:34] [main/DEBUG]: Injection complete
[16:00:34] [main/DEBUG]: Running coremod plugin for MicdoodlePlugin \{micdoodle8.mods.miccore.MicdoodlePlugin\}
[16:00:34] [main/DEBUG]: Running coremod plugin MicdoodlePlugin
[16:00:34] [main/INFO]: Failed to find MicdoodleCore file in mods folder, skipping GC version check.
[16:00:34] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[16:00:34] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[16:00:34] [main/DEBUG]: Coremod plugin class MicdoodlePlugin run successfully
[16:00:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:00:34] [main/DEBUG]: Injecting coremod LoadingPlugin \{xaero.common.core.LoadingPlugin\} class transformers
[16:00:34] [main/TRACE]: Registering transformer xaero.common.core.transformer.ChunkTransformer
[16:00:34] [main/TRACE]: Registering transformer xaero.common.core.transformer.NetHandlerPlayClientTransformer
[16:00:34] [main/DEBUG]: Injection complete
[16:00:34] [main/DEBUG]: Running coremod plugin for LoadingPlugin \{xaero.common.core.LoadingPlugin\}
[16:00:34] [main/DEBUG]: Running coremod plugin LoadingPlugin
[16:00:34] [main/DEBUG]: Coremod plugin class LoadingPlugin run successfully
[16:00:34] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[16:00:34] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@6b030101
[16:00:34] [main/DEBUG]: Injecting coremod SteveKunGLibPlugin \{stevekung.mods.stevekunglib.core.SteveKunGLibPlugin\} class transformers
[16:00:34] [main/DEBUG]: Injection complete
[16:00:34] [main/DEBUG]: Running coremod plugin for SteveKunGLibPlugin \{stevekung.mods.stevekunglib.core.SteveKunGLibPlugin\}
[16:00:34] [main/DEBUG]: Running coremod plugin SteveKunGLibPlugin
[16:00:34] [main/DEBUG]: Coremod plugin class SteveKunGLibPlugin run successfully
[16:00:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:00:34] [main/DEBUG]: Validating minecraft
[16:00:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:00:34] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:00:34] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[16:00:34] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:00:34] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[16:00:34] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[16:00:35] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:00:35] [main/INFO]: Transforming net.minecraft.entity.player.EntityPlayer finished, added func_184613_cA() overriding EntityLivingBase
[16:00:35] [main/INFO]: Transforming net.minecraft.entity.player.EntityPlayer finished, added func_184613_cA() overriding EntityLivingBase
[16:00:35] [main/INFO]: [net.minecraft.client.main.Main:main:55]: Completely ignored arguments: [--icon, C:\Users\Marcel\AppData\Roaming\.technic\assets\packs\gezuschten-cooles-modpack\icon.png, --title, Gezüschten Cooles Modpack]
[16:00:35] [main/FATAL]: Mixin apply failed mixins.stevekung's_lib.json:WorldServerMixin -> net.minecraft.world.WorldServer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method adjustPosToNearbyEntity in mixins.stevekung's_lib.json:WorldServerMixin was not located in the target class net.minecraft.world.WorldServer. Using refmap mixins.stevekung's_lib.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method adjustPosToNearbyEntity in mixins.stevekung's_lib.json:WorldServerMixin was not located in the target class net.minecraft.world.WorldServer. Using refmap mixins.stevekung's_lib.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:387) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:360) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:293) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:261) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) [More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) [More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) [More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_251]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:247) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.stevekung's_lib.json:WorldServerMixin] from phase [DEFAULT] in config [mixins.stevekung's_lib.json] FAILED during APPLY
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:247)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:00:35] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method adjustPosToNearbyEntity in mixins.stevekung's_lib.json:WorldServerMixin was not located in the target class net.minecraft.world.WorldServer. Using refmap mixins.stevekung's_lib.refmap.json
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:387)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:360)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:293)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:261)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
[16:00:35] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[16:00:35] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/WorldServer
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:247) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.WorldServer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:247) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:247) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.stevekung's_lib.json:WorldServerMixin] from phase [DEFAULT] in config [mixins.stevekung's_lib.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:247) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method adjustPosToNearbyEntity in mixins.stevekung's_lib.json:WorldServerMixin was not located in the target class net.minecraft.world.WorldServer. Using refmap mixins.stevekung's_lib.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:387) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:360) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:293) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:261) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[More-Planets-1.12.2-2.2.1-GC280.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:247) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
[16:00:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[16:00:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[16:00:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[16:00:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[16:00:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[16:00:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[16:00:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Geolykt** [comment]
I think the issue is probably at whatever defines `mixins.stevekung's_lib.json:WorldServerMixin`, it is likely written for the wrong version of the client/server, so I'd update the mod and client/server to a version where they both support each other.
I highly doubt this has anything to do with sponge's mixins

**Comment by einfachmarci** [comment]
es gibt nur 1 mod mit einer Version. Das ist das ding

**Comment by Earthcomputer** [comment]
This repository is not the place for player support.

**Comment by einfachmarci** [comment]
Das bedeutet ? :D

**Comment by Zidane** [comment]
Not a Mixin issue.

**Comment by Geolykt** [comment]
> es gibt nur 1 mod mit einer Version. Das ist das ding

Then choose the correct client version

**Comment by Earthcomputer** [comment]
> Das bedeutet ? :D

Dieser Repo ist nur für Fehler in Mixin. Dieses Problem ist nicht ein Fehler in Mixin. Bitte über Probleme mit Forge-Mods in [Forge-Forums](https://forums.minecraftforge.net/) oder [Forge-Discord](https://discord.gg/UvedJ9m) fragen.
