### ISSUE TITLE
Mixin Injection targets the wrong method

### ISSUE THREAD

**Issue by Geolykt** [SpongePowered/Mixin#478]
## Before I get started:
I am using a highly unconventional setup, where Classloading could be an issue (and would be the only thing that would explain the issue I have, outside from it being a Mixin bug). Additionally I am working in an obfuscated environment with notch-type mappings (method are like `a`, `b`, `c` and so on and are not guaranteed to have unique names) and I have no choice to do that otherwise.

## The issue:
It appears that if I inject (via `@Inject`) into a method with a parameter fails if there is also a method with the same name but no parameter.

## Example
Base class (the class I'm injecting into)
```java
package de.geolykt.starloader.impl;

public class Test {

    private void a() {
        System.out.println("Test");
    }

    private void a(int b) {
        System.out.println("Test" + b + " !");
    }

}
```

Mixin class
```java
package de.geolykt.starloader.apimixins;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import de.geolykt.starloader.impl.Test;

@Mixin(Test.class)
public class TestMixin {

    @Inject(method = "a", at = @At("HEAD"))
    private void a(int arg, CallbackInfo ci) {
        System.out.println("called with params");
    }
}
```

I have not tested if this affects other loaders, but given that Mixins has worked good so far with my classloading I would assume that this *might* be an issue with the Mixins at it's core. I have tested it to be reproducible with 0.8.0 and 0.8.3.

Error:
```
[AWT-EventQueue-0] [11:48:48.746] (MixinProcessor.handleMixinError) - FATAL - Mixin apply failed api-mixins.json:TestMixin -> de.geolykt.starloader.impl.Test: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on api-mixins.json:TestMixin->@Inject::a(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> api-mixins.json:TestMixin -> Apply Injections ->  -> Inject -> api-mixins.json:TestMixin->@Inject::a(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on api-mixins.json:TestMixin->@Inject::a(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> api-mixins.json:TestMixin -> Apply Injections ->  -> Inject -> api-mixins.json:TestMixin->@Inject::a(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
```
Stacktrace:
```
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:509) ~[starloader-1.1.0-all.jar:?]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:439) ~[starloader-1.1.0-all.jar:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[starloader-1.1.0-all.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:436) ~[starloader-1.1.0-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1283) ~[starloader-1.1.0-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[starloader-1.1.0-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[starloader-1.1.0-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[starloader-1.1.0-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[starloader-1.1.0-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:573) ~[starloader-1.1.0-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:361) ~[starloader-1.1.0-all.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:243) ~[starloader-1.1.0-all.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.minestom.server.extras.selfmodification.mixins.MixinCodeModifier.transform(MixinCodeModifier.java:42) ~[starloader-1.1.0-all.jar:?]
	at net.minestom.server.extras.selfmodification.MinestomRootClassLoader.transformBytes(MinestomRootClassLoader.java:235) ~[starloader-1.1.0-all.jar:?]
	at net.minestom.server.extras.selfmodification.MinestomExtensionClassLoader.loadClassAsChild(MinestomExtensionClassLoader.java:49) ~[starloader-1.1.0-all.jar:?]
	at net.minestom.server.extras.selfmodification.MinestomRootClassLoader.define(MinestomRootClassLoader.java:167) ~[starloader-1.1.0-all.jar:?]
	at net.minestom.server.extras.selfmodification.MinestomRootClassLoader.loadClass(MinestomRootClassLoader.java:132) ~[starloader-1.1.0-all.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minestom.server.extras.selfmodification.MinestomExtensionClassLoader.loadClass(MinestomExtensionClassLoader.java:20) ~[starloader-1.1.0-all.jar:?]
	at de.geolykt.starloader.StarloaderAPIExtension.postInitialize(StarloaderAPIExtension.java:23) ~[?:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087) ~[?:?]
	at de.geolykt.starloader.Starloader.init(Starloader.java:38) ~[starloader-1.1.0-all.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at de.geolykt.starloader.launcher.SLMouseListener.mouseClicked(SLMouseListener.java:68) ~[starloader-1.1.0-all.jar:?]
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278) ~[?:?]
	[... multiple java AWT internals that are not relevant to our case ...]
```
It should be noted that while I am using minestom internals for classloading, I am not actually using it in it's entirety (just classloading, and even then, it's modified ever so slighly)

**Comment by Earthcomputer** [comment]
When there are two methods with the same name, you need to specify which one you are targeting by using the descriptor. So you want `method = "a(I)V"` instead of what you have.

**Comment by Geolykt** [comment]
Ah that makes sense, would be good if that is specified in the docs
