### ISSUE TITLE
0.8.3-SNAPSHOT regression in locals capture

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/Mixin#480]
When applying mixins on SpongeVanilla, I get the following new error from a set of mixins that applied correctly on 0.8.2:

```
[07Apr.2021 16:31:49] [main/FATAL] [mixin/]: Mixin apply failed mixins.sponge.inventory.json:event.world.level.block.entity.HopperBlockEntityMixin_Inventory -> net.minecraft.world.level.block.entity.HopperBlockEntity: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> mixins.sponge.inventory.json:event.world.level.block.entity.HopperBlockEntityMixin_Inventory -> Apply Injections -> Inject -> mixins.sponge.inventory.json:event.world.level.block.entity.HopperBlockEntityMixin_Inventory->@Inject::impl$afterPutStackInSlots(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/Container;Lnet/minecraft/core/Direction;ILnet/minecraft/world/item/ItemStack;Lnet/minecraft/world/item/ItemStack;)V]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> mixins.sponge.inventory.json:event.world.level.block.entity.HopperBlockEntityMixin_Inventory -> Apply Injections -> Inject -> mixins.sponge.inventory.json:event.world.level.block.entity.HopperBlockEntityMixin_Inventory->@Inject::impl$afterPutStackInSlots(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/Container;Lnet/minecraft/core/Direction;ILnet/minecraft/world/item/ItemStack;Lnet/minecraft/world/item/ItemStack;)V]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1299) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:573) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:361) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:243) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:125) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:436) ~[aw-joined-1.16.5.jar:?]
	at net.minecraft.world.level.levelgen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:13) ~[aw-joined-1.16.5.jar:?]
	at net.minecraft.data.worldgen.SurfaceBuilders.<clinit>(SurfaceBuilders.java:11) ~[aw-joined-1.16.5.jar:?]
	at net.minecraft.data.BuiltinRegistries.lambda$static$0(BuiltinRegistries.java:44) ~[aw-joined-1.16.5.jar:?]
	at net.minecraft.data.BuiltinRegistries.lambda$static$6(BuiltinRegistries.java:75) ~[aw-joined-1.16.5.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:74) ~[aw-joined-1.16.5.jar:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:237) ~[aw-joined-1.16.5.jar:?]
	at net.minecraft.world.level.dimension.DimensionType.<clinit>(DimensionType.java:62) ~[aw-joined-1.16.5.jar:?]
	at org.spongepowered.common.world.SpongeWorldTypeEffect$FactoryImpl.<clinit>(SpongeWorldTypeEffect.java:52) ~[main/:?]
	at org.spongepowered.common.registry.SpongeFactoryProvider.registerDefaultFactories(SpongeFactoryProvider.java:221) ~[main/:?]
	at org.spongepowered.common.SpongeLifecycle.establishFactories(SpongeLifecycle.java:81) ~[main/:?]
	at org.spongepowered.common.SpongeBootstrap.perform(SpongeBootstrap.java:61) ~[main/:?]
	at org.spongepowered.vanilla.launch.DedicatedServerLaunch.launchPlatform(DedicatedServerLaunch.java:55) ~[launch/:?]
	at org.spongepowered.vanilla.launch.DedicatedServerLaunch.launch(DedicatedServerLaunch.java:43) ~[launch/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.spongepowered.vanilla.applaunch.handler.dev.ServerDevLaunchHandler.launchService0(ServerDevLaunchHandler.java:44) ~[applaunch/:?]
	at org.spongepowered.vanilla.applaunch.handler.AbstractVanillaLaunchHandler.lambda$launchService$1(AbstractVanillaLaunchHandler.java:162) ~[applaunch/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-8.0.9.jar:?]
	at org.spongepowered.vanilla.applaunch.Main.run(Main.java:91) ~[applaunch/:?]
	at org.spongepowered.vanilla.applaunch.Main.main(Main.java:62) ~[applaunch/:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "typeDescriptor" is null
	at org.objectweb.asm.Type.getType(Type.java:177) ~[asm-9.1.jar:9.1]
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:176) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:431) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:436) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1283) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b290.git-b1cd46c8c4960eae026bcd6dd9bafb59cafa4d52]
	... 44 more
```

The injection that failed: https://github.com/SpongePowered/Sponge/blob/6b60267a2735954c2eb66d1e4dce9bed28e388f6/src/mixins/java/org/spongepowered/common/mixin/inventory/event/world/level/block/entity/HopperBlockEntityMixin_Inventory.java#L108

The bytecode of the target method:
```java
  // access flags 0x2
  private ejectItems()Z
   L0
    LINENUMBER 149 L0
    ALOAD 0
    INVOKESPECIAL net/minecraft/world/level/block/entity/HopperBlockEntity.getAttachedContainer ()Lnet/minecraft/world/Container;
    ASTORE 1
   L1
    LINENUMBER 150 L1
    ALOAD 1
    IFNONNULL L2
   L3
    LINENUMBER 151 L3
    ICONST_0
    IRETURN
   L2
    LINENUMBER 154 L2
   FRAME APPEND [net/minecraft/world/Container]
    ALOAD 0
    INVOKEVIRTUAL net/minecraft/world/level/block/entity/HopperBlockEntity.getBlockState ()Lnet/minecraft/world/level/block/state/BlockState;
    GETSTATIC net/minecraft/world/level/block/HopperBlock.FACING : Lnet/minecraft/world/level/block/state/properties/DirectionProperty;
    INVOKEVIRTUAL net/minecraft/world/level/block/state/BlockState.getValue (Lnet/minecraft/world/level/block/state/properties/Property;)Ljava/lang/Comparable;
    CHECKCAST net/minecraft/core/Direction
    INVOKEVIRTUAL net/minecraft/core/Direction.getOpposite ()Lnet/minecraft/core/Direction;
    ASTORE 2
   L4
    LINENUMBER 155 L4
    ALOAD 0
    ALOAD 1
    ALOAD 2
    INVOKESPECIAL net/minecraft/world/level/block/entity/HopperBlockEntity.isFullContainer (Lnet/minecraft/world/Container;Lnet/minecraft/core/Direction;)Z
    IFEQ L5
   L6
    LINENUMBER 156 L6
    ICONST_0
    IRETURN
   L5
    LINENUMBER 159 L5
   FRAME APPEND [net/minecraft/core/Direction]
    ICONST_0
    ISTORE 3
   L7
   FRAME APPEND [I]
    ILOAD 3
    ALOAD 0
    INVOKEVIRTUAL net/minecraft/world/level/block/entity/HopperBlockEntity.getContainerSize ()I
    IF_ICMPGE L8
   L9
    LINENUMBER 160 L9
    ALOAD 0
    ILOAD 3
    INVOKEVIRTUAL net/minecraft/world/level/block/entity/HopperBlockEntity.getItem (I)Lnet/minecraft/world/item/ItemStack;
    INVOKEVIRTUAL net/minecraft/world/item/ItemStack.isEmpty ()Z
    IFEQ L10
   L11
    LINENUMBER 161 L11
    GOTO L12
   L10
    LINENUMBER 164 L10
   FRAME SAME
    ALOAD 0
    ILOAD 3
    INVOKEVIRTUAL net/minecraft/world/level/block/entity/HopperBlockEntity.getItem (I)Lnet/minecraft/world/item/ItemStack;
    INVOKEVIRTUAL net/minecraft/world/item/ItemStack.copy ()Lnet/minecraft/world/item/ItemStack;
    ASTORE 4
   L13
    LINENUMBER 165 L13
    ALOAD 0
    ALOAD 1
    ALOAD 0
    ILOAD 3
    ICONST_1
    INVOKEVIRTUAL net/minecraft/world/level/block/entity/HopperBlockEntity.removeItem (II)Lnet/minecraft/world/item/ItemStack;
    ALOAD 2
    INVOKESTATIC net/minecraft/world/level/block/entity/HopperBlockEntity.addItem (Lnet/minecraft/world/Container;Lnet/minecraft/world/Container;Lnet/minecraft/world/item/ItemStack;Lnet/minecraft/core/Direction;)Lnet/minecraft/world/item/ItemStack;
    ASTORE 5
   L14
    LINENUMBER 167 L14
    ALOAD 5
    INVOKEVIRTUAL net/minecraft/world/item/ItemStack.isEmpty ()Z
    IFEQ L15
   L16
    LINENUMBER 168 L16
    ALOAD 1
    INVOKEINTERFACE net/minecraft/world/Container.setChanged ()V
   L17
    LINENUMBER 169 L17
    ICONST_1
    IRETURN
   L15
    LINENUMBER 171 L15
   FRAME APPEND [net/minecraft/world/item/ItemStack]
    ALOAD 0
    ILOAD 3
    ALOAD 4
    INVOKEVIRTUAL net/minecraft/world/level/block/entity/HopperBlockEntity.setItem (ILnet/minecraft/world/item/ItemStack;)V
   L12
    LINENUMBER 159 L12
   FRAME CHOP 1
    IINC 3 1
    GOTO L7
   L8
    LINENUMBER 175 L8
   FRAME FULL [] []
    ICONST_0
    IRETURN
   L18
    LOCALVARIABLE this Lnet/minecraft/world/level/block/entity/HopperBlockEntity; L0 L18 0
    LOCALVARIABLE var0 Lnet/minecraft/world/Container; L1 L18 1
    LOCALVARIABLE var1 Lnet/minecraft/core/Direction; L4 L18 2
    LOCALVARIABLE var2 I L7 L8 3
    LOCALVARIABLE var3 Lnet/minecraft/world/item/ItemStack; L13 L12 4
    LOCALVARIABLE var4 Lnet/minecraft/world/item/ItemStack; L14 L12 5
    MAXSTACK = 5
    MAXLOCALS = 6
```

**Comment by zml2008** [comment]
It seems this wasn't entirely fixed. In our snapshots branch (21w16a), this issue is getting triggered again in another branch of `Locals`.

```
[19:28:44] [main/FATAL] [mixin]: Mixin apply failed mixins.sponge.inventory.json:event.world.level.block.entity.HopperBlockEntityMixin_Inventory -> net.minecraft.world.level.block.entity.HopperBlockEntity: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> mixins.sponge.inventory.json:event.world.level.block.entity.HopperBlockEntityMixin_Inventory -> Apply Injections -> Inject -> mixins.sponge.inventory.json:event.world.level.block.entity.HopperBlockEntityMixin_Inventory->@Inject::impl$afterPutStackInSlots(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/Container;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/Container;Lnet/minecraft/core/Direction;ILnet/minecraft/world/item/ItemStack;Lnet/minecraft/world/item/ItemStack;)V]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> mixins.sponge.inventory.json:event.world.level.block.entity.HopperBlockEntityMixin_Inventory -> Apply Injections -> Inject -> mixins.sponge.inventory.json:event.world.level.block.entity.HopperBlockEntityMixin_Inventory->@Inject::impl$afterPutStackInSlots(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/Container;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/Container;Lnet/minecraft/core/Direction;ILnet/minecraft/world/item/ItemStack;Lnet/minecraft/world/item/ItemStack;)V]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1300) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:573) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:361) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:243) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:125) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:442) ~[joined_aw-1ae6cd3ee9a87eb61f6daa2d8bd9126ddedc6f18-21w16a.jar:?]
	at net.minecraft.world.level.levelgen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:66) ~[joined_aw-1ae6cd3ee9a87eb61f6daa2d8bd9126ddedc6f18-21w16a.jar:?]
	at net.minecraft.data.worldgen.SurfaceBuilders.<clinit>(SurfaceBuilders.java:36) ~[joined_aw-1ae6cd3ee9a87eb61f6daa2d8bd9126ddedc6f18-21w16a.jar:?]
	at net.minecraft.data.BuiltinRegistries.lambda$static$0(BuiltinRegistries.java:35) ~[joined_aw-1ae6cd3ee9a87eb61f6daa2d8bd9126ddedc6f18-21w16a.jar:?]
	at net.minecraft.data.BuiltinRegistries.lambda$static$6(BuiltinRegistries.java:76) ~[joined_aw-1ae6cd3ee9a87eb61f6daa2d8bd9126ddedc6f18-21w16a.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:75) ~[joined_aw-1ae6cd3ee9a87eb61f6daa2d8bd9126ddedc6f18-21w16a.jar:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:376) ~[joined_aw-1ae6cd3ee9a87eb61f6daa2d8bd9126ddedc6f18-21w16a.jar:?]
	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:39) ~[joined_aw-1ae6cd3ee9a87eb61f6daa2d8bd9126ddedc6f18-21w16a.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:125) ~[joined_aw-1ae6cd3ee9a87eb61f6daa2d8bd9126ddedc6f18-21w16a.jar:?]
	at org.spongepowered.vanilla.launch.ClientLaunch.lambda$launchPlatform$0(ClientLaunch.java:54) ~[classes/:?]
	at org.spongepowered.common.SpongeBootstrap.perform(SpongeBootstrap.java:80) ~[classes/:?]
	at org.spongepowered.vanilla.launch.ClientLaunch.launchPlatform(ClientLaunch.java:54) ~[classes/:?]
	at org.spongepowered.vanilla.launch.ClientLaunch.launch(ClientLaunch.java:42) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.spongepowered.vanilla.applaunch.handler.dev.ClientDevLaunchHandler.launchService0(ClientDevLaunchHandler.java:44) ~[classes/:?]
	at org.spongepowered.vanilla.applaunch.handler.AbstractVanillaLaunchHandler.lambda$launchService$1(AbstractVanillaLaunchHandler.java:162) ~[classes/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-8.0.9.jar:?]
	at org.spongepowered.vanilla.applaunch.Main.run(Main.java:91) ~[classes/:?]
	at org.spongepowered.vanilla.applaunch.Main.main(Main.java:62) ~[classes/:?]
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.Type.getType(Type.java:177) ~[asm-9.1.jar:9.1]
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:275) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:431) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:436) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284) ~[mixin-0.8.3-SNAPSHOT.jar:0.8.3-SNAPSHOT+Jenkins-b292.git-5f51f16bb5effcd1bf60a66ca8a873ddf8630985]
	... 43 more

Process finished with exit code 1
```

The primary method involved here is https://github.com/SpongePowered/Sponge/blob/a3dd8a5b6b64c67616b538f80c8eea06560e90d8/src/mixins/java/org/spongepowered/common/mixin/inventory/event/world/level/block/entity/HopperBlockEntityMixin_Inventory.java#L116

`dumpTargetOnFailure` output: [HopperBlockEntity.target.class.zip](https://github.com/SpongePowered/Mixin/files/6373930/HopperBlockEntity.target.class.zip) (zipped so GH will accept it as an upload)

**Comment by Mumfrey** [comment]
I'm just going to hotpatch this as I'm going away tomorrow and don't have time to verify the root cause, and suspect it's the same as last time so verifying it would just confirm that.
