### ISSUE TITLE
Mixin fails to handle being loaded from a network path on windows.

### ISSUE THREAD

**Issue by Tom-The-Geek** [SpongePowered/Mixin#534]
## System information
- Windows 10
- Fabric loader: 0.12.5
- MultiMC 0.6.13-2517
- Mixin: 0.8.4

The game is being launched from a network share with the path `//REDACTED-SRV-FILE01/USERNAME-REDACTED/Downloads/mmc-stable-win32/MultiMC/instances/1.17.1/.minecraft`, which seems to throw some of mixin's internal file handling, resulting in the following error:

## Crash log
<details>
<summary>Click to expand</summary>
<br>

```
[12:06:29] [main/INFO]: Loading for game Minecraft 1.17.1
[12:06:29] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) recommends any version of fabric-textures-v0, which is missing!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[12:06:29] [main/INFO]: Loading 11 mods:
	- fabric-api-base 0.3.0+a02b44633d
	- fabric-key-binding-api-v1 1.0.4+a02b44633d
	- fabric-lifecycle-events-v1 1.4.4+a02b44633d
	- fabric-rendering-data-attachment-v1 0.1.5+a02b446313
	- fabric-rendering-fluids-v1 0.1.13+a02b446313
	- fabric-resource-loader-v0 0.4.7+b7ab61213d
	- fabricloader 0.12.5
	- iris 1.1.2+build.9
	- java 16
	- minecraft 1.17.1
	- sodium 0.3.2+IRIS2-build.9
[12:06:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file://LC-SRV-FILE01/[redacted]/Downloads/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.6+mixin.0.8.4/sponge-mixin-0.10.6+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalArgumentException: URI has an authority component
	at java.base/java.io.File.<init>(File.java:425)
	at org.spongepowered.asm.launch.platform.MainAttributes.getAttributes(MainAttributes.java:102)
	at org.spongepowered.asm.launch.platform.MainAttributes.<init>(MainAttributes.java:65)
	at org.spongepowered.asm.launch.platform.MainAttributes.of(MainAttributes.java:221)
	at org.spongepowered.asm.launch.platform.container.ContainerHandleURI.<init>(ContainerHandleURI.java:52)
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getPrimaryContainer(MixinServiceKnot.java:177)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.init(MixinPlatformManager.java:102)
	at org.spongepowered.asm.launch.MixinBootstrap.getPlatform(MixinBootstrap.java:118)
	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:166)
	at org.spongepowered.asm.launch.MixinBootstrap.init(MixinBootstrap.java:128)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:124)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 8 more
Exiting with -1
Process exited with code -1.
```

</details>

## Notes

Although this issue is occurring when using fabric-loader, I was told it appears to be an upstream mixin issue (see FabricMC/fabric-loader#552)

**Comment by Mumfrey** [comment]
Ok, I can see where that's happening. I've actually had issues with minecraft launching at all across symlinks on windows but never tried via a UNC path. I see you're using multimc so that presumably gets around the issues with the stock launcher.

Not sure why you chose to redact the server name in the description but not in the error message body though.

**Comment by Tom-The-Geek** [comment]
oops, didn't realise it was in the body, but was for privacy reasons

**Comment by Mumfrey** [comment]
Not really much point redacting it now as it was already emailed to anyone who watches the repository, and is accessible via the comment history.

At any rate, I'll need to check everywhere that uses `File` in Mixin and attempt to work around it incorrectly parsing the UNC path, a brief bit of googling did turn up some helpful results so hopefully should be possible to work around the issue.
