### ISSUE TITLE
Lots of minecraft errors

### ISSUE THREAD

**Issue by Kalkoen31** [SpongePowered/Mixin#568]
So when I try to start up minecraft 1.18.2 fabric with all my mods I'm getting a lot of errors, here is the output log (the errors start at the seconds part):

14:53:32.671
FabricLoader/Metadata
ForkJoinPool-1-worker-3
The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
14:53:32.800
FabricLoader
main
Loading 121 mods:
	- advanced_runtime_resource_pack 0.5.5 via carrier
	- advancednetherite 1.4.1-1.18.2
	- amecsapi 1.3.6+mc22w06a via mousewheelie
	- animal_feeding_trough 1.0.3+1.18.2
	- architectury 4.1.36
	- balm-fabric 3.0.0+0
	- bcdt_expansion 1.18.1-1.1.1
	- bclib 1.4.0
	- cardinal-components-base 4.1.4 via comforts
	- cardinal-components-entity 4.1.4 via comforts
	- carrier 1.10.0
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.0 via cloth-api
	- cloth-client-events-v0 3.2.64 via cloth-api
	- cloth-common-events-v1 3.2.64 via cloth-api
	- cloth-config 6.2.57
	- cloth-datagen-api-v1 3.2.64 via cloth-api
	- cloth-scissors-api-v1 3.2.64 via cloth-api
	- cloth-utils-v1 3.2.64 via cloth-api
	- coat 1.0.0-beta.17+mc1.18.2 via mousewheelie
- com_electronwill_night-config_core 3.6.4 via terrablender
	- com_electronwill_night-config_toml 3.6.4 via terrablender
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- comforts 1.1.2-1.18.2
	- customportalapi 0.0.1-beta50-1.18 via mining_dims
	- dual_riders 1.0.5
	- easymagic 3.3.0
	- enchantinginfuser 3.2.0
	- fabric 0.48.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.3+801ec85b60 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.2+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.3+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.2+2540745460 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.17+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.13.3
	- farsight 1.18-1.8
- ferritecore 4.2.0
	- forgeconfigapiport 3.2.0
	- friendsandfoes 1.2.6
	- geckolib3 3.0.35
	- graveyard 1.7
	- graveyard_biomes 1.1
	- guardvillagers 1.18.2-1.0.10
	- harvest_scythes 2.5.0
	- horseinboat fabric-1.1.1
	- incantationem 1.1.3+1.18.2
	- java 17
	- libcd 3.0.3+1.16.3 via skinnedlanterns
	- lithium 0.7.9
	- llamarama 1.6.1
	- logical_zoom 0.0.14
	- megaparrot 1.0.4
	- minecraft 1.18.2
	- mining_dims 1.3.5
	- mm 2.3 via harvest_scythes
	- modmenu 3.1.0
	- mousewheelie 1.8.8+mc1.18.2
	- no_null_processors 2.0.1+1.18.1
	- nukes 1.0.1
	- omega-config 1.2.3-1.18.1 via friendsandfoes
	- org_joml_joml 1.10.2 via sodium
	- pugh_lib 1.3.0 via mining_dims
	- puzzleslib 3.3.1
- roughlyenoughitems 8.0.441
	- skinnedlanterns 1.2.0+build.12
	- skyvillages 1.0.1-1.18.1-fabric
	- smoothboot 1.18.2-1.7.0
	- sodium 0.4.1+build.15
	- spark 1.8.14
	- starlight 1.0.2+fabric.89b8d9f
	- terrablender 1.1.0.94
	- torohealth 1.18-fabric-2
	- transportables 1.1
	- tweed4_annotated 1.3.0+mc1.18.2 via mousewheelie
	- tweed4_base 1.5.0+mc1.18.2 via mousewheelie
	- tweed4_data 1.2.1+mc1.18.2 via mousewheelie
	- tweed4_data_hjson 1.1.0+mc1.18.2 via mousewheelie
	- tweed4_tailor_coat 1.1.2+mc1.18.2 via mousewheelie
	- tweed4_tailor_screen 1.1.1+mc1.18.2 via mousewheelie
	- waystones 10.0.0
	- xaerominimap 22.3.1.1
	- xaeroworldmap 1.20.5
	- yungsapi 1.18.2-Fabric-2.0.7
14:53:32.871
FabricLoader/Metadata
main
Mod `horseinboat` (fabric-1.1.1) does not respect SemVer - comparison support is limited.
14:53:32.872
FabricLoader/Metadata
main
Mod `terrablender` (1.1.0.94) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
14:53:32.872
FabricLoader/Metadata
main
Mod `xaerominimap` (22.3.1.1) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
14:53:33.077
FabricLoader/Mixin
main
SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/maxva/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
14:53:33.227
FabricLoader/Mixin
main
Compatibility level set to JAVA_17
14:53:33.678
Lithium
main
Loaded configuration file for Lithium: 100 options available, 1 override(s) found
14:53:33.728
Sodium
main
Loaded configuration file for Sodium: 29 options available, 0 override(s) found
14:53:34.357
ferritecore-mixin
main
Mixin malte0811.ferritecore.mixin.threaddetec.PalettedContainerMixin is disabled automatically as lithium is installed
14:53:34.425
Lithium
main
Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
14:53:34.565
FabricLoader/Mixin
main
Error loading class: net/minecraft/class_5382 (java.lang.ClassNotFoundException: net/minecraft/class_5382)
14:53:34.565
FabricLoader/Mixin
main
@Mixin target net.minecraft.class_5382 was not found no_null_processors.mixins.json:RegistryReadOpsMixin
14:53:34.881
ARRP
main
I used the json to destroy the json
14:53:34.884
Sodium
main
Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
14:53:35.094
Smooth Boot
main
Smooth Boot config initialized
14:53:39.805
FabricLoader/Mixin
main
@Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zno000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
14:53:42.385
FabricLoader/Mixin
main
Error loading class: net/minecraft/class_5323 (java.lang.ClassNotFoundException: net/minecraft/class_5323)

14:53:42.386
FabricLoader
main
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1869 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1869 failed
	at net.minecraft.class_1865.<clinit>(class_1865.java:14)
	at net.minecraft.class_2378.method_17797(class_2378.java:203)
	at net.minecraft.class_2378.method_40280(class_2378.java:352)
	at net.minecraft.class_2378.method_34031(class_2378.java:300)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_2378.<clinit>(class_2378.java:299)
	at net.minecraft.class_2966.method_12851(class_2966.java:49)
	at net.minecraft.client.main.Main.main(Main.java:153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1869 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 15 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 25 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for mixins.libcd.json:MixinShapedRecipe during activity: [Transform -> Method loadResource(Lcom/google/gson/JsonObject;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> INVOKESTATIC -> net/minecraft/class_5323::method_29223:()Lnet/minecraft/class_5415;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 28 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.class_5323
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 34 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5323
	... 38 more
14:53:42.639
launcher
main

14:53:42.639
monitor
Process Monitor
Process crashed with exit code 1

**Comment by Zidane** [comment]
**This is not a support forum**

This is for the Mixin project itself, take this to Fabric's discord or somewhere else please.
