### ISSUE TITLE
How to use mixin without launchwrapper

### ISSUE THREAD

**Issue by ChAoSUnItY** [SpongePowered/Mixin#575]
I am attempting using mixin in a clean Java gradle project, with main method for entry point of my application, but when I attempting to run the Main.java (a), it throws an excetion telling me no service available (b), is there any full guide how to make it working?

Main.java (a)
```java
package io.github.chaosunity;

import org.spongepowered.asm.launch.MixinBootstrap;
import org.spongepowered.asm.mixin.Mixins;

public class Main {
    public static void main(String[] args) {
        MixinBootstrap.init();
        Mixins.addConfiguration("mixin.example.json");
    }
}
```

Exception (b)
```java
Exception in thread "main" org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available. Services: INVALID[ModLauncher] and 1 other invalid services.
	at org.spongepowered.asm.service.MixinService.initService(MixinService.java:159)
	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:125)
	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:120)
	at org.spongepowered.asm.mixin.MixinEnvironment.<init>(MixinEnvironment.java:946)
	at org.spongepowered.asm.mixin.MixinEnvironment$Phase.getEnvironment(MixinEnvironment.java:152)
	at org.spongepowered.asm.mixin.MixinEnvironment.getEnvironment(MixinEnvironment.java:1357)
	at org.spongepowered.asm.mixin.MixinEnvironment.getDefaultEnvironment(MixinEnvironment.java:1366)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at io.github.chaosunity.Main.main(Main.java:8)
```

**Comment by Mumfrey** [comment]
This is an issue tracker for reporting bugs and requesting features. For questions please use dicord.

Your question translates to *"I am building a car and would like to use your custom gearbox, but I don't want to use an engine."* so I think there's something you're misunderstanding.

[Link to `#mixin` discord channel](https://discord.gg/tBcwxz2)
