### ISSUE TITLE
server does not boot with spongeforge 

### ISSUE THREAD

**Issue by weston343** [SpongePowered/Mixin#605]
This is the issue im having doesnt matter ive tried most recent and version ive seen in a fix reccomended nothing works also renamed spongeforge.jar  to aaa another person with same issue said it fixed their issue with mixins but now i have mojang launcher wrapper error idk what that means its one problem after another
<html>
<body>

[09:12:38] ain/ERROR] [LaunchWrapper]: Unable to launch
--
java.lang.ClassNotFoundException: net.minecraft.server.MinecraftServer
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_331]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_331]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_331]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_331]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_331]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_331]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_331]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_331]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2847-universal.jar:?]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2847-universal.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[aaa.jar:1.12.2-2838-7.1.7]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
... 12 more
Caused by: java.lang.AbstractMethodError
at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1212) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1126) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:274) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[aaa.jar:1.12.2-2838-7.1.7]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
... 12 more
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: java.lang.reflect.InvocationTargetException
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at java.lang.reflect.Method.invoke(Unknown Source)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.SecurityManager.checkExit(Unknown Source)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Runtime.exit(Unknown Source)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.System.exit(Unknown Source)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:12:38] ain/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: ... 6 more

</body>
</html>

**Comment by weston343** [comment]
> This repo is for issues and bugs with Mixin.

what is all the rrors about the mixins then instead of explain where the issue belongs you closed it with no reason your a GOOFY bro... wtf how about some help here brainiac

**Comment by weston343** [comment]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[aaa.jar:1.12.2-2838-7.1.7]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
... 12 more
Caused by: java.lang.AbstractMethodError
at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1212) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1126) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:274) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[aaa.jar:1.12.2-2838-7.1.7]
at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[aaa.jar:1.12.2-2838-7.1.7]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
... 12 more

**Comment by TheKodeToad** [comment]
This is most likely not related to mixin - more the mixins.
