### ISSUE TITLE
Crashing when activate dropper with item

### ISSUE THREAD

**Issue by Maks2005X** [SpongePowered/Mixin#633]
Hi! When i activate dropper with item the serverver is crashing. 
Version is Fabric 1.20.

Crash log:
---- Minecraft Crash Report ----
// Sorry :(

Time: 2023-07-03 00:03:45
Description: Exception ticking world

org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_2325::method_10012(Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;)V has incompatible changes at opcode 131 in callback carpet-shadow.mixins.json:fragility.DropperBlockMixin from mod carpet-shadow->@Inject::fix_dispense(Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_2345;Lnet/minecraft/class_2601;ILnet/minecraft/class_1799;Lnet/minecraft/class_2350;Lnet/minecraft/class_1263;Lnet/minecraft/class_1799;)V.
 Expected: [Lnet/minecraft/class_2345;, Lnet/minecraft/class_2601;, I, Lnet/minecraft/class_1799;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_1263;, Lnet/minecraft/class_1799;]
    Found: [Lnet/minecraft/class_2345;, Lnet/minecraft/class_2601;, I, Lnet/minecraft/class_1799;, Lnet/minecraft/class_1799;]
Available: [Lnet/minecraft/class_2345;, Lnet/minecraft/class_2601;, I, Lnet/minecraft/class_1799;, Lnet/minecraft/class_1799;]
	at net.minecraft.class_2325.handler$bnf000$carpet-shadow$fix_dispense$missing(class_2325.java)
	at net.minecraft.class_2325.method_10012(class_2325.java:68)
	at net.minecraft.class_2315.method_9588(class_2315.java:113)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1113)
	at net.minecraft.class_3218.method_14189(class_3218.java:728)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:323)
	at net.minecraft.server.MinecraftServer.redirect$bek000$carpet-fixes$catchExceptions(MinecraftServer.java:4831)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.handler$zhh000$carpet$modifiedRunLoop(MinecraftServer.java:10942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by Mumfrey** [comment]
This is an issue tracker for bugs and feature requests for Mixin, crashes related to mods using it should be raised against the mod in question.
