### ISSUE TITLE
Thread: Render thread Suspected Mod:  	Patchouli (patchouli), Version: 1.20.1-83-FORGE

### ISSUE THREAD

**Issue by Akkkkkkpo** [SpongePowered/Mixin#648]
Stacktrace:
	at vazkii.patchouli.common.util.ItemStackUtil.loadFromParsed(ItemStackUtil.java:77) ~[Patchouli-1.20.1-83-FORGE.jar%23598!/:1.20.1-83-FORGE] {re:classloading}
	at vazkii.patchouli.common.book.Book.lambda$new$1(Book.java:162) ~[Patchouli-1.20.1-83-FORGE.jar%23598!/:1.20.1-83-FORGE] {re:mixin,re:classloading}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%23109!/:?] {}
	at vazkii.patchouli.common.book.Book.getBookItem(Book.java:174) ~[Patchouli-1.20.1-83-FORGE.jar%23598!/:1.20.1-83-FORGE] {re:mixin,re:classloading}
	at vazkii.patchouli.common.util.ItemStackUtil.getBookFromStack(ItemStackUtil.java:122) ~[Patchouli-1.20.1-83-FORGE.jar%23598!/:1.20.1-83-FORGE] {re:classloading}
	at vazkii.patchouli.client.handler.TooltipHandler.onTooltip(TooltipHandler.java:44) ~[Patchouli-1.20.1-83-FORGE.jar%23598!/:1.20.1-83-FORGE] {re:classloading}
	at vazkii.patchouli.forge.client.ForgeClientInitializer.lambda$onInitializeClient$12(ForgeClientInitializer.java:147) ~[Patchouli-1.20.1-83-FORGE.jar%23598!/:1.20.1-83-FORGE] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onRenderTooltipPre(ForgeHooksClient.java:1034) ~[forge-1.20.1-47.2.6-universal.jar%23689!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.dynamic_resources.ForgeHooksClientMixin,pl:mixin:APP:bcc.forge.mixins.json:ForgeClientHooksMixin,pl:mixin:APP:sodium-extra.mixins.json:fog.ForgeHooksClientMixin,pl:mixin:A}
	at net.minecraft.client.gui.GuiGraphics.m_280497_(GuiGraphics.java:591) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280677_(GuiGraphics.java:562) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.renderTooltip(GuiGraphics.java:556) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280072_(AbstractContainerScreen.java:163) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:highlighter.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.client.AbstractContainerScreenMixin,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.client.accessor.AbstractContainerScreenAccessor,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:controllable.common.mixins.json:client.ContainerScreenMixin,pl:mixin:APP:vivecraft.mixins.json:client_vr.gui.screens.inventory.AbstractContainerScreenVRMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_88315_(InventoryScreen.java:80) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:recipeessentials.mixins.json:InventoryButtonMixin,pl:mixin:APP:highlighter.mixins.json:InventoryScreenMixin,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinInventoryScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23684!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:yungsmenutweaks.mixins.json:ScreenMixin,pl:mixin:APP:cumulus_menus.mixins.json:client.accessor.ScreenAccessor,pl:mixin:APP:kiwi.mixins.json:client.ScreenMixin,pl:mixin:APP:aether.mixins.json:client.accessor.ScreenAccessor,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:konkrete.mixin.json:IMixinScreen,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:vivecraft.mixins.json:client.gui.screens.ScreenMixin,pl:mixin:APP:vivecraft.mixins.json:client_vr.gui.screens.ScreenVRMixin,pl:mixin:APP:vivecraft.dynamicfps.mixins.json:DynamicFPSScreenVRMixin,pl:mixin:APP:fancymenu.general.mixin.json:IMixinScreen,pl:mixin:APP:fancymenu.general.mixin.json:MixinScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.6-universal.jar%23689!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.dynamic_resources.ForgeHooksClientMixin,pl:mixin:APP:bcc.forge.mixins.json:ForgeClientHooksMixin,pl:mixin:APP:sodium-extra.mixins.json:fog.ForgeHooksClientMixin,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.6-universal.jar%23689!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.dynamic_resources.ForgeHooksClientMixin,pl:mixin:APP:bcc.forge.mixins.json:ForgeClientHooksMixin,pl:mixin:APP:sodium-extra.mixins.json:fog.ForgeHooksClientMixin,pl:mixin:A}

**Comment by Zidane** [comment]
This issue tracker is for issues with the Mixin library and usage of it. Not for individual mod or modpack support.
