### ISSUE TITLE
Modpack Server Crash

### ISSUE THREAD

**Issue by MrLinusK** [SpongePowered/Mixin#662]
[19:35:42] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[19:35:42] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[19:35:42] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[19:35:42] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[19:35:42] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_401, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre-1.8
[19:35:43] [main/INFO] [FML]: Searching C:\Users\linus\Desktop\Server\.\mods for mods
[19:35:43] [main/INFO] [FML]: Searching C:\Users\linus\Desktop\Server\.\mods\1.12.2 for mods
[19:35:43] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from !mixinbooter-7.0.jar
[19:35:43] [main/INFO] [FML]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[19:35:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.2.31.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:43] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:43] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[19:35:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:43] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:43] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[19:35:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Galacticraft-1.12.2-4.0.4 (1).jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:43] [main/WARN] [FML]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[19:35:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Galacticraft-1.12.2-4.0.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:43] [main/WARN] [FML]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[19:35:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Mekanism-1.12.2-9.8.3.390.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:43] [main/WARN] [FML]: The coremod mekanism.coremod.MekanismCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:43] [main/WARN] [FML]: The coremod MekanismCoremod (mekanism.coremod.MekanismCoremod) is not signed!
[19:35:43] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from More-Planets-1.12.2-2.2.4-GC284.jar
[19:35:43] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in OpenComputers-MC1.12.2-1.7.7+5413028.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:43] [main/WARN] [FML]: The coremod li.cil.oc.common.launch.TransformerLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:43] [main/WARN] [FML]: The coremod TransformerLoader (li.cil.oc.common.launch.TransformerLoader) is not signed!
[19:35:43] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from SteveKunG's-Lib-1.12.2-1.2.0.jar
[19:35:43] [main/WARN] [FML]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:43] [main/WARN] [FML]: The coremod IELoadingPlugin (blusunrize.immersiveengineering.common.asm.IELoadingPlugin) is not signed!
[19:35:43] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:35:43] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[19:35:43] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/linus/Desktop/Server/./mods/!mixinbooter-7.0.jar Service=LaunchWrapper Env=SERVER
[19:35:44] [main/WARN] [FML]: The coremod MixinBooter (zone.rong.mixinbooter.MixinBooterPlugin) is not signed!
[19:35:44] [main/INFO] [MixinBooter]: MixinBootstrap Initializing...
[19:35:44] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[19:35:44] [main/INFO] [SteveKunG's Lib]: Initializing SteveKunG's Lib plugin!
[19:35:44] [main/WARN] [FML]: The coremod SteveKunGLibPlugin (stevekung.mods.stevekunglib.core.SteveKunGLibPlugin) is not signed!
[19:35:44] [main/INFO] [LaunchWrapper]: Loading tweak class name codechicken.asm.internal.Tweaker
[19:35:44] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[19:35:44] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[19:35:44] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:35:44] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:35:44] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:35:44] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:35:45] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:35:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:35:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:35:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:35:45] [main/INFO] [MicdoodleCore]: Successfully Registered Transformer
[19:35:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:35:45] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[19:35:45] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@5d1e09bc
[19:35:45] [main/INFO] [LaunchWrapper]: Calling tweak class codechicken.asm.internal.Tweaker
[19:35:45] [main/INFO] [STDOUT]: [codechicken.asm.internal.Tweaker:injectIntoClassLoader:30]: false
[19:35:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:35:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:35:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:35:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:35:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:35:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:35:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:35:46] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[19:35:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:35:46] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[19:35:46] [main/ERROR] [MicdoodleCore]: Potential problem: Galacticraft did not complete injection of bytecode into: amu (0 / 1)
[19:35:46] [main/ERROR] [MicdoodleCore]: Potential problem: Galacticraft did not complete injection of bytecode into: amu (0 / 1)
[19:35:46] [main/INFO] [EnderCore ASM]: Transforming net.minecraft.entity.player.EntityPlayer finished, added func_184613_cA() overriding EntityLivingBase
[19:35:46] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:230]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[19:35:46] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:242]: Transforming net.minecraft.block.Block Finished.
[19:35:47] [main/ERROR] [MicdoodleCore]: Potential problem: Galacticraft did not complete injection of bytecode into: axw (0 / 1)
[19:35:47] [main/ERROR] [MicdoodleCore]: Potential problem: Galacticraft did not complete injection of bytecode into: pl (0 / 4)
[19:35:47] [main/INFO] [EnderCore ASM]: Transforming net.minecraft.entity.player.EntityPlayer finished, added func_184613_cA() overriding EntityLivingBase
[19:35:47] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[19:35:47] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:230]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[19:35:47] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:242]: Transforming net.minecraft.block.Block Finished.
[19:35:47] [main/ERROR] [MicdoodleCore]: Potential problem: Galacticraft did not complete injection of bytecode into: acl (0 / 1)
[19:35:48] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_401]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_401]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_401]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_401]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_401]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_401]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_401]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2860.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/monster/EntitySnowman
        at net.minecraft.block.Block.func_149671_p(Block.java:2432) ~[aow.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.monster.EntitySnowman
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.block.Block.func_149671_p(Block.java:2432) ~[aow.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/monster/EntityGolem
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_401]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.block.Block.func_149671_p(Block.java:2432) ~[aow.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.monster.EntityGolem
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_401]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.block.Block.func_149671_p(Block.java:2432) ~[aow.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.ClassFormatError: Duplicate method name "canBreath" with signature "()Z" in class file net/minecraft/entity/monster/EntityGolem
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_401]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_401]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
        at net.minecraft.block.Block.func_149671_p(Block.java:2432) ~[aow.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
        ... 12 more
A problem occurred running the Server launcher.[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: java.lang.reflect.InvocationTargetException
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at java.lang.reflect.Method.invoke(Unknown Source)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at java.lang.SecurityManager.checkExit(Unknown Source)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at java.lang.Runtime.exit(Unknown Source)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at java.lang.System.exit(Unknown Source)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:35:48] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        ... 6 more

**Comment by zml2008** [comment]
This is an issue tracker not a support forum. Please talk with the makers of the mod pack for more help, since what you have reported does not appear to be a Mixin issue.
