### ISSUE TITLE
[1.8] MixinTweaker causing NPE on initialization

### ISSUE THREAD

**Issue by olee** [SpongePowered/Mixin#68]
Mixin crashes on 1.8 with a NPE when trying to access the not yet initialized `side` variable of `FMLLaunchHandler`.
This access is caused by initializing the forge `SideTransformer` class.
This is the relevant stacktrace:
````
Thread [main] (Suspended (breakpoint at line 102 in FMLLaunchHandler))	
	FMLLaunchHandler.side() line: 102	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: not available	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: not available	
	Method.invoke(Object, Object...) line: not available	
	MixinEnvironment$Side$2(MixinEnvironment$Side).getSideName(String, String) line: 175	
	MixinEnvironment$Side$2(MixinEnvironment$Side).getSideName() line: 153	
	MixinEnvironment$Side$2.detect() line: 134	
	MixinEnvironment.getSide() line: 661	
	MixinEnvironment.<init>(MixinEnvironment$Phase) line: 475	
	MixinEnvironment.getEnvironment(MixinEnvironment$Phase) line: 844	
	MixinEnvironment.init(MixinEnvironment$Phase) line: 828	
	MixinBootstrap.preInit() line: 142	
	MixinTweaker.<init>() line: 78	
	NativeConstructorAccessorImpl.newInstance0(Constructor<?>, Object[]) line: not available [native method]	
	NativeConstructorAccessorImpl.newInstance(Object[]) line: not available	
	DelegatingConstructorAccessorImpl.newInstance(Object[]) line: not available	
	Constructor<T>.newInstance(Object...) line: not available	
	Class<T>.newInstance() line: not available	
	Launch.launch(String[]) line: 98	
	Launch.main(String[]) line: 28	
	GradleStart(GradleStartCommon).launch(String[]) line: not available	
	GradleStart.main(String[]) line: not available	
````

Important trace parts
````
	FMLLaunchHandler.side() line: 102	
	...
	MixinTweaker.<init>() line: 78	
````

~~Basically the `MixinTweaker` should **not** be initialized before the `SideTransformer` of Forge.~~
Actually the `MixinTweaker` should not call `MixinBootstrap.preInit()` at all until the `FMLTweaker` has been run.

**Comment by olee** [comment]
Ok found that it actually crashes here when the returned `side` is `null`.
````
        // org.spongepowered.asm.mixin.MixinEnvironment.Side
        private String getSideName(String className, String methodName) {
            try {
                Class<?> clazz = Class.forName(className, false, Launch.classLoader);
                Method method = clazz.getDeclaredMethod(methodName);
                return ((Enum<?>)method.invoke(null)).name();
            } catch (Exception ex) {
                return null;
            }
        }
````

A simple fix should probably be changing
````
return ((Enum<?>)method.invoke(null)).name();
````
to
````
Enum<?> sideEnum = (Enum<?>) method.invoke(null);
if (sideEnum != null)
    return sideEnum.name();
````

**Comment by olee** [comment]
Ok I did some mistake in tracing back the problem.
Here is the crash stacktrace I got:
````
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ExceptionInInitializerError
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:218)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer.<init>(Unknown Source)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:118)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at GradleStart.main(Unknown Source)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.<clinit>(SideTransformer.java:32)
[03:47:51] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 18 more
````

**Comment by Mumfrey** [comment]
This shouldn't happen any more as of 0.4.5, are you sure this is happening with the latest build?

**Comment by liach** [comment]
@olee https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/1256009ca5362a2afcf2b3a268f964e23494d55b#diff-c197962302397baf3a4cc36463dce5eaR118

So this issue is invalid. Ummmm...

**Comment by olee** [comment]
Oh.....
Yeah I already found this in the build.gradle:
````
	shade "org.spongepowered:mixin:0.4.4"
	shadeClient "org.spongepowered:mixin:0.4.5-SNAPSHOT"
````
... and then fell asleep before I could finish fixing it.
