### ISSUE TITLE
MixinAgent JVM crash on startup

### ISSUE THREAD

**Issue by michaelvdnet** [SpongePowered/Mixin#681]
Trying to get mixin hotswapping to work with Fabric.
Followed the fabric docs: https://docs.fabricmc.net/develop/getting-started/launching-the-game#hotswapping-mixins

But the JVM crashes on debug startup with the following error:
```
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.For more details on the daemon, please refer to https://docs.gradle.org/8.10/userguide/gradle_daemon.html in the Gradle documentation.
Process command line: C:\Users\Michael\.jdks\jbr-21.0.3-windows-x64-b509.15\bin\java.exe --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -XX:+AllowEnhancedClassRedefinition -javaagent:C:\Users\Michael\.gradle\caches\modules-2\files-2.1\net.fabricmc\sponge-mixin\0.15.3+mixin.0.8.7\51ee0a44ab05f6fddd66b09e66b3a16904f9c55d\sponge-mixin-0.15.3+mixin.0.8.7.jar -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=127.0.0.1:7933 --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx1G -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\Michael\.gradle\wrapper\dists\gradle-8.10-bin\deqhafrv1ntovfmgh0nh3npr9\gradle-8.10\lib\gradle-daemon-main-8.10.jar -javaagent:C:\Users\Michael\.gradle\wrapper\dists\gradle-8.10-bin\deqhafrv1ntovfmgh0nh3npr9\gradle-8.10\lib\agents\gradle-instrumentation-agent-8.10.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.10
Please read the following process output to find out more:
-----------------------
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/tree/ClassNode
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2846)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:521)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.tree.ClassNode
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 5 more
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message Outstanding error when calling method in invokeJavaAgentMainMethod at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 627
*** java.lang.instrument ASSERTION FAILED ***: "success" with message invokeJavaAgentMainMethod failed at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 466
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 429
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed

-----------------------
Check the JVM arguments defined for the gradle process in:
 - gradle.properties in project root directory
```

VM Options:
```
-XX:+AllowEnhancedClassRedefinition
-javaagent:"C:\Users\Michael\.gradle\caches\modules-2\files-2.1\net.fabricmc\sponge-mixin\0.15.3+mixin.0.8.7\51ee0a44ab05f6fddd66b09e66b3a16904f9c55d\sponge-mixin-0.15.3+mixin.0.8.7.jar"
```

Versions:
```
Jetbrains Runtime: jbr-21.0.3-windows-x64-b509.15
sponge-mixin: 0.15.3+mixin.0.8.7
IDEA: 2024.2.2
OS: Windows 11
```

Also tried with jbr-17, same error

**Comment by Geolykt** [comment]
You might need to also include the dependencies of mixin on the classpath, but I'm slightly confused by the fact that you're attempting to launch the gradle daemon with the mixin javaagent - but I have never really modded Minecraft so what can I tell.
Unlikely to be a mixin bug (completely ignoring that fabric's sponge-mixin is a fork of Sponge's Mixin library - i.e. this repository).

**Comment by michaelvdnet** [comment]
>completely ignoring that fabric's sponge-mixin is a fork of Sponge's Mixin library - i.e. this repository

Completely missed that (should've known).

Continuing over at https://github.com/FabricMC/Mixin/issues/159
