### ISSUE TITLE
Transformer fails to resolve nonvirtual default method invocations in Java 8

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#76]
I know that invoke specials were handled in #71, but there's an issue at runtime in dev workspace, plainly, if I have an interface that has a method as:
```java
public interface IMixinCustom {
  default void foo(List<Bar> bar) { }
}
```
and the following mixin:

```java
public abstract class MixinCustomA implements IMixinCustom {

}
```

```java
public abstract class MixinCustomB extends MixinCustomA {

  @Override
  public void foo(List<Bar> bar) {
    super.foo(bar);
    foo.add(new Bar());
  }
}
```

The following stack trace will occur (in relative terms, I have IMixinEntity, MixinEntity not overriding the method, and MixinEntitySheep extending MixinEntity that is overriding and calling super):

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
Exception in thread "Client thread" 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
	at GradleStart.main(Unknown Source) [start/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/item/EntityXPOrb
	at net.minecraft.init.Bootstrap.register(Bootstrap.java:643) ~[Bootstrap.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:346) ~[Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:117) ~[Main.class:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.item.EntityXPOrb
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_60]
	at net.minecraft.init.Bootstrap.register(Bootstrap.java:643) ~[Bootstrap.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:346) ~[Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:117) ~[Main.class:?]
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.MixinTransformerError: Error resolving INVOKESPECIAL for org/spongepowered/common/mixin/core/entity/MixinEntity.supplyVanillaManipulators(Ljava/util/List;)V in mixins.common.core.json:entity.MixinEntityXPOrb
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.updateBinding(MixinTargetContext.java:486) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.updateStaticBinding(MixinTargetContext.java:458) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethodRef(MixinTargetContext.java:278) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:233) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMethods(MixinApplicator.java:292) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.applyMixin(MixinApplicator.java:206) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:189) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:644) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:616) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:434) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:105) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_60]
	at net.minecraft.init.Bootstrap.register(Bootstrap.java:643) ~[Bootstrap.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:346) ~[Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:117) ~[Main.class:?]
	... 17 more
```

As I understand it, the super call is still supposed to work in traditional Java, but I'm assuming that in this case, it's not resolving to call the method from the interface.

**Comment by Mumfrey** [comment]
This is because Mixin was designed for Java 6 and doesn't even attempt to resolve nonvirtual targets in super interfaces, this behaviour can easily be rectified.
