### ISSUE TITLE
NPE on getting obfuscated methods

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/Mixin#90]
Getting this NPE while trying to build SpongeForge, no real reason or telling which method is throwing it:

```
Caused by: java.lang.NullPointerException
        at org.spongepowered.tools.obfuscation.AnnotatedMixins.getObfMethod(AnnotatedMixins.java:657)
        at org.spongepowered.tools.obfuscation.AnnotatedMixin.remapReference(AnnotatedMixin.java:611)
        at org.spongepowered.tools.obfuscation.AnnotatedMixin.registerInjectionPoint(AnnotatedMixin.java:573)
        at org.spongepowered.tools.obfuscation.AnnotatedMixins.registerInjector(AnnotatedMixins.java:526)
        at org.spongepowered.tools.obfuscation.InjectionObfuscationProcessor.processInjectors(InjectionObfuscationProcessor.java:103)
        at org.spongepowered.tools.obfuscation.InjectionObfuscationProcessor.process(InjectionObfuscationProcessor.java:71)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 87 more

```
Full stack trace: https://gist.github.com/gabizou/be14f00a015b7829e096

**Comment by Mumfrey** [comment]
This is not relevant to 0.4.10

**Comment by Mumfrey** [comment]
Here's your boy: [MixinEntity#L123](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java#L123)

**Comment by Mumfrey** [comment]
Here too apparently: [MixinEntityPlayer#62](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayer.java#L62)
