### ISSUE TITLE
Proper setup for hybrid plugin to add additional mixin configuration without a tweaker

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Mixin#95]
**Not a Sponge Issue**

@Mumfrey , as you know I asked you yesterday a bit about this but I think I either didn't understand or something is up.

With Almura for 1.8.9, I use MixinGradle (which is a thing of beauty) and the AP works with no issue so I assume that production is fine (not tested but everything seems to be "there"). My issue seems to be with the dev environment:

In my run configuration, I put an entry of ```--mixin mixins.almura.default.json``` on my **Program Arguments** but it never seems to load it from Almura's classpath. Here are some things to help:

***build.gradle***
```groovy
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            name = 'oss-sonatype-public'
            url = 'https://oss.sonatype.org/content/repositories/public/'
        }
        maven {
            name = 'forge'
            url = 'http://files.minecraftforge.net/maven/'
        }
        maven {
            name = 'sponge'
            url = 'http://repo.spongepowered.org/maven'
        }
        maven {
            url = 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
        classpath 'gradle.plugin.nl.javadude.gradle.plugins:license-gradle-plugin:0.12.0'
        classpath 'org.spongepowered:mixingradle:0.2-SNAPSHOT'
        classpath 'org.spongepowered:spongegradle:0.3-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'com.github.hierynomus.license'
apply plugin: 'org.spongepowered.mixin'
apply plugin: 'org.spongepowered.gradle'

defaultTasks 'clean', 'licenseFormat', 'sortAccessTransformers', 'build'

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

archivesBaseName = project.name.toLowerCase()
version = "${project.minecraftVersion}-${project.forgeVersion}-r${project.apiVersion.split("-")[0]}"

sourceSets {
    main {
        refMap = "mixins.${project.name.toLowerCase()}.refmap.json"
    }
}

minecraft {
    forgeVersion = project.forgeVersion
    runDir = 'run'
    mappings = project.mcpMappings
    makeObfSourceJar = false
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = 'oss-sonatype-public'
        url = 'https://oss.sonatype.org/content/repositories/public/'
    }
    maven {
        name = 'sponge-public'
        url = 'http://repo.spongepowered.org/maven/'
    }
}

dependencies {
    compile('org.spongepowered:mixin:0.4.14-SNAPSHOT') {
        exclude module: 'launchwrapper'
        exclude module: 'guava'
    }
    compile 'org.spongepowered:spongeapi:3.1.0-SNAPSHOT'
}

idea {
    module {
        inheritOutputDirs = true
    }
}

license {
    ext.name = project.name
    ext.organization = project.organization
    ext.url = project.url
    header rootProject.file('HEADER.txt')
    ignoreFailures true
    strictCheck true
    include '**/*.java'
}

if (JavaVersion.current().isJava8Compatible() || JavaVersion.current().isJava9Compatible()) {
    tasks.withType(Javadoc) {
        // disable the crazy super-strict doclint tool in Java 8
        options.addStringOption('Xdoclint:none', '-quiet')
    }
}

compileJava {
    options.compilerArgs += [
            '-Xlint:-processing',
    ]
    options.deprecation = true
    options.encoding = 'utf8'
}

jar {
    manifest {
        attributes(
                'Built-By': System.properties['user.name'],
                'Created-By': System.properties['java.vm.version'] + ' (' + System.properties['java.vm.vendor'] + ')',
                'Implementation-Title': project.name,
                'Implementation-Version': version,
                'Implementation-Vendor': url,
                'MixinConfigs': 'mixins.almura.default.json',
                'FMLAT': 'almura_at.cfg'
        )
    }
}
```

***mixins.almura.default.json***
```json
{
    "package": "com.almuradev.almura.mixin",
    "refmap": "mixins.almura.refmap.json",
    "mixins": [
        "block.MixinBlockTallGrass",
        "block.MixinBlockWall",
        "inventory.MixinContainerWorkbench",
        "item.crafting.MixinShapedRecipes",
        "item.crafting.MixinShapelessRecipes",
        "network.play.client.MixinC01PacketChatMessage",
        "network.play.client.MixinC12PacketUpdateSign",
        "network.play.server.MixinS33PacketUpdateSign",
        "network.MixinNetHandlerPlayServer",
        "tileentity.MixinTileEntitySign",
        "world.MixinWorld"
    ],
    "client": [
        "client.entity.MixinEntityClientPlayerMP",
        "client.gui.inventory.MixinGuiEditSign",
        "client.gui.MixinGuiChat",
        "client.gui.MixinGuiIngameForge",
        "client.gui.MixinGuiNewChat",
        "client.renderer.entity.MixinRender",
        "client.renderer.entity.MixinRenderPlayer",
        "client.renderer.entity.MixinRendererLivingEntity",
        "client.renderer.tileentity.MixinRenderItemFrame",
        "client.renderer.tileentity.MixinTileEntityChestRenderer",
        "client.renderer.tileentity.MixinTileEntitySignRenderer",
        "client.settings.MixinGameSettings"
    ]
}
```

***run configuration***
http://imgur.com/scxzCSW

I'll stress again that the IDE is loading Almura with Sponge but I get no printout from this simple mixin:

```java
/**
 * This file is part of Almura, All Rights Reserved.
 *
 * Copyright (c) AlmuraDev <http://github.com/AlmuraDev/>
 */
package com.almuradev.almura.mixin.world;

import net.minecraft.world.World;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

@Mixin(World.class)
public abstract class MixinWorld {
    @Inject(method = "init", at = @At("RETURN"))
    public void testMixins(CallbackInfoReturnable<World> cir) {
        System.err.println("Seems to work...");
    }
}
```

I actually get no printout about the fact that ***all the other mixins are not there***. I might be mistaken but I'm fairly sure that Mixin will complain when you specify a mixin that doesn't exist.

Thoughts?

**Comment by Mumfrey** [comment]
If specifying `--mixin` on the command-line, you may also need to specify the tweaker itself on the command-line  with `--tweakClass org.spongepowered.asm.launch.MixinTweaker` in order for it to actually *receive* said command-line argument.

**Comment by Zidane** [comment]
@Mumfrey 

Interesting. I didn't think it would be needed since SpongeForge is loading the tweaker. I'll give it a shot.

**Comment by Zidane** [comment]
@Mumfrey 

I'll be dammed, that did it XD. All is well! Do I need to specify that in my manifest for production (tweak class) or is what I have fine?

**Comment by Mumfrey** [comment]
> I didn't think it would be needed since SpongeForge is loading the tweaker.

No in dev environment the tweaker is not normally loaded, Mixin is bootstrapped via the coremod directly.

> Do I need to specify that in my manifest for production (tweak class) or is what I have fine?

Since you're declaring `MixinConfigs` in your manifest, yes you must also declare the tweaker. This is because even if the tweaker is already loaded, it uses the declaration of the tweaker to locate other jars which require mixin's attention.

**Comment by Zidane** [comment]
@Mumfrey 

Alright so I've made those changes but now I have a new issue:

With putting ```--tweakClass org.spongepowered.asm.launch.MixinTweaker --mixin mixins.almura.default.json``` on the program arguments, I think its no longer using any of Sponge's mixin configs:

```
2016-01-22 12:43:28,644 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-01-22 12:43:28,646 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[12:43:28] [main/INFO] [GradleStart]: Extra: [--tweakClass, org.spongepowered.asm.launch.MixinTweaker, --mixin, mixins.almura.default.json]
[12:43:28] [main/INFO] [GradleStart]: Running with arguments: [--tweakClass, net.minecraftforge.fml.common.launcher.FMLServerTweaker, --tweakClass, org.spongepowered.asm.launch.MixinTweaker, --mixin, mixins.almura.default.json, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[12:43:28] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[12:43:28] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[12:43:28] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[12:43:29] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.4.12 Source=file:/C:/Users/csanders/.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.4.12-SNAPSHOT/baff40cf6b0d0c420ac72626837fa46258aa031c/mixin-0.4.12-SNAPSHOT.jar Env=SERVER
[12:43:29] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[12:43:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[12:43:31] [main/INFO] [FML]: Forge Mod Loader version 11.15.0.1694 for Minecraft 1.8.9 loading
[12:43:31] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jdk1.8.0_51\jre
[12:43:31] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[12:43:31] [main/INFO] [FML]: Found a command line coremod : org.spongepowered.mod.SpongeCoremod
[12:43:31] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[12:43:31] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[12:43:31] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[12:43:31] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[12:43:31] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[12:43:33] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@55dfcc6
[12:43:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[12:43:33] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[12:43:33] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[12:43:33] [main/INFO] [GradleStart]: Injecting location in coremod org.spongepowered.mod.SpongeCoremod
[12:43:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:43:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:43:33] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[12:43:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[12:43:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:43:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:43:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:33] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[12:43:35] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[12:43:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:43:35] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[12:43:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:43:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[12:43:35] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[12:43:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[12:43:38] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[12:43:42] [Server thread/INFO]: Starting minecraft server version 1.8.9
[12:43:42] [Server thread/INFO] [FML]: MinecraftForge v11.15.0.1694 Initialized
[12:43:42] [Server thread/INFO] [FML]: Replaced 204 ore recipies
[12:43:44] [Server thread/DEBUG] [Sponge]: Sponge Timings: true - Verbose: false - Interval: 1m - Length: 3m
[12:43:46] [Server thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[12:43:46] [Server thread/INFO] [FML]: Searching D:\Projects\SpongeDev\SpongeForge\run\mods for mods
[12:43:53] [Server thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.logging.InternalLoggerFactory]: Using SLF4J as the default logging framework
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent0]: java.nio.Buffer.address: available
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent0]: sun.misc.Unsafe.theUnsafe: available
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent0]: sun.misc.Unsafe.copyMemory: available
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent0]: java.nio.Bits.unaligned: true
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent]: Platform: Windows
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent]: Java version: 8
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent]: -Dio.netty.noUnsafe: false
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent]: sun.misc.Unsafe: available
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent]: -Dio.netty.noJavassist: false
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent]: Javassist: unavailable
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent]: You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent]: -Dio.netty.tmpdir: C:\Users\csanders\AppData\Local\Temp (java.io.tmpdir)
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent]: -Dio.netty.bitMode: 64 (sun.arch.data.model)
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.PlatformDependent]: -Dio.netty.noPreferDirect: false
[12:43:53] [Server thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, sponge, almura] at CLIENT
[12:43:53] [Server thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, sponge, almura] at SERVER
[12:43:53] [Server thread/DEBUG] [io.netty.util.internal.ThreadLocalRandom]: -Dio.netty.initialSeedUniquifier: 0xb71e8efe3b7e0924 (took 2 ms)
[12:43:53] [Server thread/DEBUG] [io.netty.buffer.ByteBufUtil]: -Dio.netty.allocator.type: unpooled
[12:43:53] [Server thread/DEBUG] [io.netty.buffer.ByteBufUtil]: -Dio.netty.threadLocalDirectBufferSize: 65536
[12:43:53] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[12:43:53] [Server thread/INFO] [FML]: Found 384 ObjectHolder annotations
[12:43:53] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[12:43:53] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[12:43:53] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[12:43:53] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
> Jan 22, 2016 12:43:53 PM com.google.common.eventbus.EventBus$LoggingSubscriberExceptionHandler handleException
[12:43:53] [Server thread/INFO] [FML]: Applying holder lookups
SEVERE: Could not dispatch event: sponge to public void org.spongepowered.mod.SpongeMod.onStateEvent(net.minecraftforge.fml.common.event.FMLStateEvent)
[12:43:53] [Server thread/INFO] [FML]: Holder lookups applied
[12:43:53] [Server thread/INFO] [FML]: Injecting itemstacks
[12:43:53] [Server thread/INFO] [FML]: Itemstack injection complete
[12:43:53] [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[12:43:53] [Server thread/ERROR] [FML]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8.9-11.15.0.1694-PROJECT(SpongeForge).jar) 
	UCH	Forge{11.15.0.1694} [Minecraft Forge] (forgeSrc-1.8.9-11.15.0.1694-PROJECT(SpongeForge).jar) 
	UCE	sponge{$version} [SpongeForge] (SpongeForge) 
	UCH	almura{1.8.9-1694-r3.1} [Almura] (Almura) 
[12:43:53] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[12:43:53] [Server thread/ERROR] [FML]: Caught exception from sponge
java.lang.ClassCastException: net.minecraftforge.fml.common.LoadController cannot be cast to org.spongepowered.mod.interfaces.IMixinLoadController
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:228) ~[SpongeForge/:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:277) ~[SpongeForge/:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:245) ~[SpongeForge/:?]
	at org.spongepowered.api.service.SimpleServiceManager.setProvider(SimpleServiceManager.java:84) ~[main/:?]
	at org.spongepowered.mod.SpongeMod.registerService(SpongeMod.java:160) ~[SpongeForge/:?]
	at org.spongepowered.mod.SpongeMod.onPreInit(SpongeMod.java:192) ~[SpongeForge/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[forgeSrc-1.8.9-11.15.0.1694-PROJECT(SpongeForge).jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[forgeSrc-1.8.9-11.15.0.1694-PROJECT(SpongeForge).jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:554) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.startServer(DedicatedServer.java:115) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:508) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[12:43:53] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ClassCastException: net.minecraftforge.fml.common.LoadController cannot be cast to org.spongepowered.mod.interfaces.IMixinLoadController
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:228) ~[SpongeForge/:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:277) ~[SpongeForge/:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:245) ~[SpongeForge/:?]
	at org.spongepowered.api.service.SimpleServiceManager.setProvider(SimpleServiceManager.java:84) ~[main/:?]
	at org.spongepowered.mod.SpongeMod.registerService(SpongeMod.java:160) ~[SpongeForge/:?]
	at org.spongepowered.mod.SpongeMod.onPreInit(SpongeMod.java:192) ~[SpongeForge/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:554) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.startServer(DedicatedServer.java:115) ~[DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:508) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[12:43:53] [Server thread/ERROR]: This crash report has been saved to: D:\Projects\SpongeDev\SpongeForge\run\.\crash-reports\crash-2016-01-22_12.43.53-server.txt
[12:43:53] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
> Jan 22, 2016 12:43:53 PM com.google.common.eventbus.EventBus$LoggingSubscriberExceptionHandler handleException
[12:43:53] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
SEVERE: Could not dispatch event: sponge to public void org.spongepowered.mod.SpongeMod.onStateEvent(net.minecraftforge.fml.common.event.FMLStateEvent)
[12:43:53] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
[12:43:53] [Forge Version Check/DEBUG] [ForgeVersionCheck]: [Forge] Received version check data:
{
  "homepage": "http://files.minecraftforge.net/maven/net/minecraftforge/forge/",
  "promos": {
    "1.5.2-latest": "7.8.1.738",
    "1.5.2-recommended": "7.8.1.737",
    "1.6.1-latest": "8.9.0.775",
    "1.6.2-latest": "9.10.1.871",
    "1.6.2-recommended": "9.10.1.871",
    "1.6.3-latest": "9.11.0.878",
    "1.6.4-latest": "9.11.1.1345",
    "1.6.4-recommended": "9.11.1.1345",
    "1.7.10-latest": "10.13.4.1614",
    "1.7.10-latest-1.7.10": "10.13.2.1343",
    "1.7.10-recommended": "10.13.4.1558",
    "1.7.2-latest": "10.12.2.1147",
    "1.7.2-recommended": "10.12.2.1121",
    "1.8-latest": "11.14.4.1577",
    "1.8-recommended": "11.14.4.1563",
    "1.8.8-latest": "11.15.0.1655",
    "1.8.9-latest": "11.15.0.1715",
    "latest": "11.15.0.1715",
    "latest-1.7.10": "10.13.2.1343",
    "recommended": "11.14.4.1563"
  }
}
[12:43:53] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Found status: BETA_OUTDATED Target: 11.15.0.1715
[12:43:53] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ClassCastException: net.minecraftforge.fml.common.LoadController cannot be cast to org.spongepowered.mod.interfaces.IMixinLoadController
[12:43:53] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:228)
[12:43:53] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:277)
[12:43:53] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:183)
[12:43:53] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.common.SpongeImpl.postShutdownEvents(SpongeImpl.java:187)
[12:43:53] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.dedicated.DedicatedServer.postGameStoppingEvent(DedicatedServer.java:68)
[12:43:53] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.dedicated.DedicatedServer.systemExitNow(DedicatedServer.java)
[12:43:53] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:612)
[12:43:53] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)
```

If I remove the ```--tweakClass org.spongepowered.asm.launch.MixinTweaker``` Almura and Sponge load fine but I get no mixins from Almura (of course).

**Comment by Zidane** [comment]
@Mumfrey 

As an update, I just decided to add a loading plugin to Almura which initializes the bootstrap + adds my mixin config. Not what I'd like to do but this allowed mixins to work again.

Note that I didn't need to provide any manifest entries for letting FML/Mixin know about Almura's actual plugin...Sponge still loaded Almura (which was nice).

Keep in mind I've yet to test this outside IDE so subject to changes...
