### ISSUE TITLE
Overriding default SRG class mappings using extra SRG files

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/Mixin#96]
So I was trying to make the anonymous inner class mappings in SpongeVanilla use the refmap instead. For that, I let SpongeGradle generate a [SRG file for them](https://gist.github.com/Minecrell/813fd2464142f443bff8), and added that as an extra SRG file to the mixin extension using the latest MixinGradle.

Now the problem is that Mixin refuses to load them because there are is already a key mapped to the specific value I'm trying to map to. Because the mappings generated by FG contain the (kind of useless) class mappings which just map `SRG class name -> SRG class name` for the searge mappings, when my SRG file is applied there will be one class name mapped to two different source classes for a short time until all the mappings in the SRG file are fully applied.

```

java.lang.IllegalArgumentException: value already present: net/minecraft/command/PlayerSelector$4
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
        at net.minecraftforge.srg2source.rangeapplier.SrgContainer.readSrg(SrgContainer.java:46)
        at org.spongepowered.tools.obfuscation.TargetObfuscationEnvironment.initSrgs(TargetObfuscationEnvironment.java:116)
        at org.spongepowered.tools.obfuscation.TargetObfuscationEnvironment.getObfClass(TargetObfuscationEnvironment.java:197)
        at org.spongepowered.tools.obfuscation.ObfuscationManager.getObfClass(ObfuscationManager.java:285)
        at org.spongepowered.tools.obfuscation.ObfuscationManager.getObfClass(ObfuscationManager.java:273)
        at org.spongepowered.tools.obfuscation.AnnotatedMixin.addSoftTarget(AnnotatedMixin.java:242)
        at org.spongepowered.tools.obfuscation.AnnotatedMixin.initTargets(AnnotatedMixin.java:218)
        at org.spongepowered.tools.obfuscation.AnnotatedMixin.<init>(AnnotatedMixin.java:150)
        at org.spongepowered.tools.obfuscation.AnnotatedMixins.registerMixin(AnnotatedMixins.java:286)
        at org.spongepowered.tools.obfuscation.MixinProcessor.processMixins(MixinProcessor.java:65)
        at org.spongepowered.tools.obfuscation.TargetObfuscationProcessor.process(TargetObfuscationProcessor.java:61)
```

I kind of found a hack for this problem, resetting the values I'm going to map with dummy classes first (e.g. [this SRG file](https://gist.github.com/Minecrell/b12c720af4c9de5e376e)), however I was wondering if you have any better idea how to solve this problem?

**Comment by Minecrell** [comment]
One option might be to simply ignore class mappings which map the original class name to the same class name when reading the SRG files in Mixin, haven't looked into the Mixin code but I think that could also prevent the creation of redundant refmap entries like `"net/minecraft/tileentity/TileEntitySign$2": "net/minecraft/tileentity/TileEntitySign$2",`

**Comment by Mumfrey** [comment]
Oh that's kind of annoying, didn't realise BiMap wouldn't let you just replace the entries. This is happening during the actual loading/parsing of the SRG. I think the best solution would be to just remove the Srg2Source dependency, then just make my own modified version of `SrgContainer` which uses `BiMap::forcePut` rather than `Bimap::put`

**Comment by Minecrell** [comment]
Yep, that sounds like a good idea as well.
